// Package journalhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package journalhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganizeRequestContractVersion.
const (
	JournalOrganizeV1 OrganizeRequestContractVersion = "journal-organize-v1"
)

// Valid indicates whether the value is a known member of the OrganizeRequestContractVersion enum.
func (e OrganizeRequestContractVersion) Valid() bool {
	switch e {
	case JournalOrganizeV1:
		return true
	default:
		return false
	}
}

// Defines values for TagType.
const (
	Event        TagType = "event"
	Mood         TagType = "mood"
	Organization TagType = "organization"
	Other        TagType = "other"
	Person       TagType = "person"
	Place        TagType = "place"
	Topic        TagType = "topic"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case Event:
		return true
	case Mood:
		return true
	case Organization:
		return true
	case Other:
		return true
	case Person:
		return true
	case Place:
		return true
	case Topic:
		return true
	default:
		return false
	}
}

// BookContext defines model for BookContext.
type BookContext struct {
	ContainsEntry bool               `json:"containsEntry"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestID"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ExistingBookRecommendation defines model for ExistingBookRecommendation.
type ExistingBookRecommendation struct {
	BookID openapi_types.UUID `json:"bookID"`
	Reason string             `json:"reason"`
}

// NewBookSuggestion defines model for NewBookSuggestion.
type NewBookSuggestion struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Reason      string   `json:"reason"`
	RelatedTags []string `json:"relatedTags"`
}

// OrganizeQuota defines model for OrganizeQuota.
type OrganizeQuota struct {
	Available              bool `json:"available"`
	DailyTokensRemaining   int  `json:"dailyTokensRemaining"`
	MonthlyTokensRemaining int  `json:"monthlyTokensRemaining"`
}

// OrganizeRequest defines model for OrganizeRequest.
type OrganizeRequest struct {
	Body             string                         `json:"body"`
	Books            []BookContext                  `json:"books"`
	ContentHash      string                         `json:"contentHash"`
	ContractVersion  OrganizeRequestContractVersion `json:"contractVersion"`
	ExistingTags     []string                       `json:"existingTags"`
	RejectedTagNames []string                       `json:"rejectedTagNames"`
	RequestID        openapi_types.UUID             `json:"requestID"`
	Title            string                         `json:"title"`
}

// OrganizeRequestContractVersion defines model for OrganizeRequest.ContractVersion.
type OrganizeRequestContractVersion string

// OrganizeResponse defines model for OrganizeResponse.
type OrganizeResponse struct {
	AnalysisVersion             string                       `json:"analysisVersion"`
	ContentHash                 string                       `json:"contentHash"`
	ExistingBookRecommendations []ExistingBookRecommendation `json:"existingBookRecommendations"`
	NewBookSuggestions          []NewBookSuggestion          `json:"newBookSuggestions"`
	Quota                       OrganizeQuota                `json:"quota"`
	RequestID                   openapi_types.UUID           `json:"requestID"`
	Tags                        []Tag                        `json:"tags"`
}

// Tag defines model for Tag.
type Tag struct {
	Name string  `json:"name"`
	Type TagType `json:"type"`
}

// TagType defines model for Tag.Type.
type TagType string

// RequestIDHeader defines model for RequestIDHeader.
type RequestIDHeader = openapi_types.UUID

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// OrganizeJournalParams defines parameters for OrganizeJournal.
type OrganizeJournalParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// OrganizeJournalJSONRequestBody defines body for OrganizeJournal for application/json ContentType.
type OrganizeJournalJSONRequestBody = OrganizeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(c *gin.Context, params OrganizeJournalParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// OrganizeJournal operation middleware
func (siw *ServerInterfaceWrapper) OrganizeJournal(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrganizeJournalParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OrganizeJournal(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/ai/operations/journal.organize/responses", wrapper.OrganizeJournal)
}

type BadGatewayJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type OrganizeJournalRequestObject struct {
	Params OrganizeJournalParams
	Body   *OrganizeJournalJSONRequestBody
}

type OrganizeJournalResponseObject interface {
	VisitOrganizeJournalResponse(w http.ResponseWriter) error
}

type OrganizeJournal200JSONResponse OrganizeResponse

func (response OrganizeJournal200JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OrganizeJournal401JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal403JSONResponse struct{ ForbiddenJSONResponse }

func (response OrganizeJournal403JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal409JSONResponse struct{ ConflictJSONResponse }

func (response OrganizeJournal409JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response OrganizeJournal413JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response OrganizeJournal422JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response OrganizeJournal429JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal502JSONResponse struct{ BadGatewayJSONResponse }

func (response OrganizeJournal502JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response OrganizeJournal503JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournaldefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response OrganizeJournaldefaultJSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(ctx context.Context, request OrganizeJournalRequestObject) (OrganizeJournalResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// OrganizeJournal operation middleware
func (sh *strictHandler) OrganizeJournal(ctx *gin.Context, params OrganizeJournalParams) {
	var request OrganizeJournalRequestObject

	request.Params = params

	var body OrganizeJournalJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizeJournal(ctx, request.(OrganizeJournalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizeJournal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(OrganizeJournalResponseObject); ok {
		if err := validResponse.VisitOrganizeJournalResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFldchu5Eb4KCtnHIYeUvBubb7TlzTL2ehVZTqVKpVQ1Z5okLAwwBjC0xioeIMlTbpATpHKB3CZJ5Rip",
	"xvyTI/44G+WNxAz69+v+gJ4HHukk1QqVs3zywFMwkKBD4/9d4acMrZtd/IAQo6ElofiEr4q/AVeQIJ/w",
	"3w2uUcpcZ59X4AblrsHsggfc4KdMGIz5xJkMA26jFSZAkhbaJOD4hGeZiHnAXZ6SLOuMUEu+2Wxos021",
	"suiNeQnxr8DhZ8jpX6SVQ+XoJ6SpFBE4oVX40WpFa42abwwu+IT/ImwcDYunNnxtjDZXpZJCZYw2MiIl",
	"YXzCL41eixgNW4CQGDNtmEGXGYUxA8WEWoMUMTNoM+mGfBPwV1otpIjc09k4ZQZTCXnARIxJqh2qKA/I",
	"VOvAIYtKi5iOoswYjL2dXuwTGqkY0jusSqk34ntt5iKOUT2dIdcrZBFIiYYJyyBzK1SOdGHM5pljEqI7",
	"y9wKWYVcRi84iQmqIsWXkEsN8bXWb8Es8WltN0VxMbyPEGNLKNQpGq9vYFOMxEJEzIovyKRIRGHxezRr",
	"EeEHBWsQEuYSnxaeZSBtYQaLMUUVE0wpB1ljlTf2WusfQeVlF7FPZ+lvMu2A6ibSylcKGeiDyAxCtCor",
	"54Mi1GgjvlBXe7IwNkgVWpGVWuHAiYTgnMJcSOFy5ttR8UbRsUqLU6MjtJZi/JrQnP9/QLsWWoLDor4S",
	"ULD0VWeFQmsp7M5ARJDdVERRdH6t716RsfeFsXEsSDjIS0PYd4IIYgHSYsDT1lLhIghlXytnvM8lycy1",
	"lgiKb1v7wBO4f4tq6VZ88t1otMNKARfxEeRVMWNH3vhsFPBEqPr/Lue1+fKGe8leUNfMYMuv21qQnn/E",
	"yNX9/QIdCHlyzGJshapxKSEELfufmeqk0PN0yysvv5HW3vuoIzXATnMFK5I7iOAyUtu2FgJ6zboX1gm1",
	"JGxeYaSTBFVReSfaONf6rgjbQUwZBLuD0rNnJ6KqVFiL6/PuHX4mx95nyyXar3Dq1KL6qmr56oDQRupD",
	"8TUsvbnCYWK3xBwhJYH7WbHzef0UjIGcBzxT4lOG5WM6+m6nobeuS4e6BvYl6CezBCW+oOesE5PTOQT0",
	"NEQQMr/Wd6jsFSYgFHlLsRFKJFnCJ00ChXK4RONjoZVbnbxvKya9qh+VHbQ82Rej8iRxcl3G+S52e9FL",
	"FdXF0b5+02azDojGZ9sw2gQVSf8AdlXcz5xDQ7z6+xsYLEaDF7cP3z3bfNPXLio+/S0aWxZipBUFgn/U",
	"mVEgB7oM0WA97pOAZZP72erk2/HZEZVCoKAkevy/gwSfWnmLyw42ZX836Otd+7two2Q3Ud2sVyqCApJb",
	"WemJVQXI/TXxVYQKCmRuhW1BquP284Pp+C/wjI9S7vHFt4e2O1g5361Etc2Jx2vdpdOOsrNdZZ+qvr5P",
	"bJcETkfudlXv03UNByjvEMAbOG+DqLRkf4J741/FqQ/pZPBp4O45hBzRX4qFB46KOO6Gp2gKCk8lRFS1",
	"ZY+FkuJxTXeugDudisiTm6bsaLfC9knzkbZRnhr8S7te07UJo8wIl7+nvBV+TdN06hxaN7WWvC3qtntL",
	"ewkWv3s2QEWn85hN05QVexhUm9hCG39xi0BpJSKQ9b1uLlQs1HLIg2Pmg40ZDYRS8QY98Gtj32Be4Lhr",
	"6BUuhXVoukbeYc5ETPfjhUBzpB1vMC9mlI8b8U6rCHeN+Km+eq9ASlRLpJt3hkcqLqTu03vVLuSu7rf6",
	"M5oILLIPH2YXbK4zFTOhnPa5qbN1pCmdWe3j9lyLBK2DJO1JyPev2Pn5+YsWUFz19pFGNNJ7bLjANUqd",
	"JqjcNHJiXd+xjhB8getBa9OOdCoYoRZ616tXNcanadrM1epRm62r4Z9//uM//v6Xf/3hT//+69+qmcZg",
	"OmPLYlY9ZNcrZEtUtBFjlmZzKaJ61sFAWs2EimQWl3MRuwJC96UERy18ejkb1meACf91cXJjP5bTk+mM",
	"TS9nPODripL5eDgajih0OkUFqeATfj4cD0fUk8CtfE8IVwjSrb7wycMm4KFBiPPqz3ocgggbV8PytDis",
	"TothZy6f6uJsXW+YxVQi5bulvV5382nhpp9smlfC7U8Pm9ua3l6WJ/OfZX61fUnYdDtufSRsOXw2Gv0P",
	"1O+boJZjPT9CdUwvGBEmAxUzOukx21Cin/c9G40f01s7EnbGmH7T+eFNzcDe73hxeEf9PYQ2jI9QsT1d",
	"p31nZ8f4szvk9HuPMHJ75LwJ+LejI3S2Pkn5LUe41zOK9wlfQCbd4e3FZ5s20fti6qP4m9tdNu2sleTW",
	"WWsRT2e9RQA3t1SLxeHxhjf1PZ3x203TP6oTbLVCbdRpg6HSxNJRfXCvXvB6wppRdx/dYd5ajHEdtr7M",
	"2BCKRo/NK53HzoCy9E5Ha2rEGqI8pItx+Q1060kMbTdSo+MscjasOj0IeujzYdZVb9v5iEh7CgbKjCTa",
	"ci61kzCEVAyr7uoa4hpGVGC7zE98FDd82BE3CcPx2S+p9Q/Hk+ej5yPeSlN1uOUVq3jx5VoJyfZSabJt",
	"rxVAqO5K9fLrVpC7Inz8OhLSVHbUVOBpvzPjm9vNfwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
