// Package journalhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package journalhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganizeRequestContractVersion.
const (
	JournalOrganizeV1 OrganizeRequestContractVersion = "journal-organize-v1"
)

// Valid indicates whether the value is a known member of the OrganizeRequestContractVersion enum.
func (e OrganizeRequestContractVersion) Valid() bool {
	switch e {
	case JournalOrganizeV1:
		return true
	default:
		return false
	}
}

// Defines values for TagType.
const (
	Event        TagType = "event"
	Mood         TagType = "mood"
	Organization TagType = "organization"
	Other        TagType = "other"
	Person       TagType = "person"
	Place        TagType = "place"
	Topic        TagType = "topic"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case Event:
		return true
	case Mood:
		return true
	case Organization:
		return true
	case Other:
		return true
	case Person:
		return true
	case Place:
		return true
	case Topic:
		return true
	default:
		return false
	}
}

// BookContext defines model for BookContext.
type BookContext struct {
	ContainsEntry bool               `json:"containsEntry"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestID"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ExistingBookRecommendation defines model for ExistingBookRecommendation.
type ExistingBookRecommendation struct {
	BookID openapi_types.UUID `json:"bookID"`
	Reason string             `json:"reason"`
}

// NewBookSuggestion defines model for NewBookSuggestion.
type NewBookSuggestion struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Reason      string   `json:"reason"`
	RelatedTags []string `json:"relatedTags"`
}

// OrganizeQuota defines model for OrganizeQuota.
type OrganizeQuota struct {
	Available              bool `json:"available"`
	DailyTokensRemaining   int  `json:"dailyTokensRemaining"`
	MonthlyTokensRemaining int  `json:"monthlyTokensRemaining"`
}

// OrganizeRequest defines model for OrganizeRequest.
type OrganizeRequest struct {
	Body             string                         `json:"body"`
	Books            []BookContext                  `json:"books"`
	ContentHash      string                         `json:"contentHash"`
	ContractVersion  OrganizeRequestContractVersion `json:"contractVersion"`
	ExistingTags     []string                       `json:"existingTags"`
	RejectedTagNames []string                       `json:"rejectedTagNames"`
	RequestID        openapi_types.UUID             `json:"requestID"`
	Title            string                         `json:"title"`
}

// OrganizeRequestContractVersion defines model for OrganizeRequest.ContractVersion.
type OrganizeRequestContractVersion string

// OrganizeResponse defines model for OrganizeResponse.
type OrganizeResponse struct {
	AnalysisVersion             string                       `json:"analysisVersion"`
	ContentHash                 string                       `json:"contentHash"`
	ExistingBookRecommendations []ExistingBookRecommendation `json:"existingBookRecommendations"`
	NewBookSuggestions          []NewBookSuggestion          `json:"newBookSuggestions"`
	Quota                       OrganizeQuota                `json:"quota"`
	RequestID                   openapi_types.UUID           `json:"requestID"`
	Tags                        []Tag                        `json:"tags"`
}

// Tag defines model for Tag.
type Tag struct {
	Name string  `json:"name"`
	Type TagType `json:"type"`
}

// TagType defines model for Tag.Type.
type TagType string

// VoiceSessionRequest defines model for VoiceSessionRequest.
type VoiceSessionRequest struct {
	ConsentVersion string             `json:"consentVersion"`
	SessionID      openapi_types.UUID `json:"sessionID"`
}

// VoiceSessionTicket defines model for VoiceSessionTicket.
type VoiceSessionTicket struct {
	MaximumMilliseconds   int                `json:"maximumMilliseconds"`
	RemainingMilliseconds int                `json:"remainingMilliseconds"`
	ResetsAt              time.Time          `json:"resetsAt"`
	SessionID             openapi_types.UUID `json:"sessionID"`
	Token                 string             `json:"token"`
}

// RequestIDHeader defines model for RequestIDHeader.
type RequestIDHeader = openapi_types.UUID

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// OrganizeJournalParams defines parameters for OrganizeJournal.
type OrganizeJournalParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// CreateJournalVoiceSessionParams defines parameters for CreateJournalVoiceSession.
type CreateJournalVoiceSessionParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// OrganizeJournalJSONRequestBody defines body for OrganizeJournal for application/json ContentType.
type OrganizeJournalJSONRequestBody = OrganizeRequest

// CreateJournalVoiceSessionJSONRequestBody defines body for CreateJournalVoiceSession for application/json ContentType.
type CreateJournalVoiceSessionJSONRequestBody = VoiceSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(c *gin.Context, params OrganizeJournalParams)
	// CreateJournalVoiceSession Admit an authenticated subscriber to a resumable voice session.
	// (POST /v1/journal/voice/sessions)
	CreateJournalVoiceSession(c *gin.Context, params CreateJournalVoiceSessionParams)
	// StreamJournalVoiceSession Upgrade to the voice protocol with a single-use bearer ticket.
	// (GET /v1/journal/voice/sessions/{sessionID}/stream)
	StreamJournalVoiceSession(c *gin.Context, sessionID openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// OrganizeJournal operation middleware
func (siw *ServerInterfaceWrapper) OrganizeJournal(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrganizeJournalParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OrganizeJournal(c, params)
}

// CreateJournalVoiceSession operation middleware
func (siw *ServerInterfaceWrapper) CreateJournalVoiceSession(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateJournalVoiceSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateJournalVoiceSession(c, params)
}

// StreamJournalVoiceSession operation middleware
func (siw *ServerInterfaceWrapper) StreamJournalVoiceSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "sessionID" -------------
	var sessionID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionID", c.Param("sessionID"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamJournalVoiceSession(c, sessionID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/journal/voice/sessions", wrapper.CreateJournalVoiceSession)
	router.GET(options.BaseURL+"/v1/journal/voice/sessions/:sessionID/stream", wrapper.StreamJournalVoiceSession)
	router.POST(options.BaseURL+"/v1/ai/operations/journal.organize/responses", wrapper.OrganizeJournal)
}

type BadGatewayJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type OrganizeJournalRequestObject struct {
	Params OrganizeJournalParams
	Body   *OrganizeJournalJSONRequestBody
}

type OrganizeJournalResponseObject interface {
	VisitOrganizeJournalResponse(w http.ResponseWriter) error
}

type OrganizeJournal200JSONResponse OrganizeResponse

func (response OrganizeJournal200JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OrganizeJournal401JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal403JSONResponse struct{ ForbiddenJSONResponse }

func (response OrganizeJournal403JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal409JSONResponse struct{ ConflictJSONResponse }

func (response OrganizeJournal409JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response OrganizeJournal413JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response OrganizeJournal422JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response OrganizeJournal429JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal502JSONResponse struct{ BadGatewayJSONResponse }

func (response OrganizeJournal502JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response OrganizeJournal503JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournaldefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response OrganizeJournaldefaultJSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJournalVoiceSessionRequestObject struct {
	Params CreateJournalVoiceSessionParams
	Body   *CreateJournalVoiceSessionJSONRequestBody
}

type CreateJournalVoiceSessionResponseObject interface {
	VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error
}

type CreateJournalVoiceSession201JSONResponse VoiceSessionTicket

func (response CreateJournalVoiceSession201JSONResponse) VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJournalVoiceSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateJournalVoiceSessiondefaultJSONResponse) VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamJournalVoiceSessionRequestObject struct {
	SessionID openapi_types.UUID `json:"sessionID"`
}

type StreamJournalVoiceSessionResponseObject interface {
	VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error
}

type StreamJournalVoiceSession101Response struct {
}

func (response StreamJournalVoiceSession101Response) VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type StreamJournalVoiceSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response StreamJournalVoiceSessiondefaultJSONResponse) VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(ctx context.Context, request OrganizeJournalRequestObject) (OrganizeJournalResponseObject, error)
	// CreateJournalVoiceSession Admit an authenticated subscriber to a resumable voice session.
	// (POST /v1/journal/voice/sessions)
	CreateJournalVoiceSession(ctx context.Context, request CreateJournalVoiceSessionRequestObject) (CreateJournalVoiceSessionResponseObject, error)
	// StreamJournalVoiceSession Upgrade to the voice protocol with a single-use bearer ticket.
	// (GET /v1/journal/voice/sessions/{sessionID}/stream)
	StreamJournalVoiceSession(ctx context.Context, request StreamJournalVoiceSessionRequestObject) (StreamJournalVoiceSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// OrganizeJournal operation middleware
func (sh *strictHandler) OrganizeJournal(ctx *gin.Context, params OrganizeJournalParams) {
	var request OrganizeJournalRequestObject

	request.Params = params

	var body OrganizeJournalJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizeJournal(ctx, request.(OrganizeJournalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizeJournal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(OrganizeJournalResponseObject); ok {
		if err := validResponse.VisitOrganizeJournalResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateJournalVoiceSession operation middleware
func (sh *strictHandler) CreateJournalVoiceSession(ctx *gin.Context, params CreateJournalVoiceSessionParams) {
	var request CreateJournalVoiceSessionRequestObject

	request.Params = params

	var body CreateJournalVoiceSessionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJournalVoiceSession(ctx, request.(CreateJournalVoiceSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJournalVoiceSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateJournalVoiceSessionResponseObject); ok {
		if err := validResponse.VisitCreateJournalVoiceSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamJournalVoiceSession operation middleware
func (sh *strictHandler) StreamJournalVoiceSession(ctx *gin.Context, sessionID openapi_types.UUID) {
	var request StreamJournalVoiceSessionRequestObject

	request.SessionID = sessionID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StreamJournalVoiceSession(ctx, request.(StreamJournalVoiceSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamJournalVoiceSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StreamJournalVoiceSessionResponseObject); ok {
		if err := validResponse.VisitStreamJournalVoiceSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FpZchu5Gb4KCplHkk1KHsfmG215MoqXUbRMUqVSqn42fpKw0EAbQNOiVTxAkqfcICdI5QK5TZLKMVIA",
	"emeLi+JRMm8iGv+K798A3dNYJamSKK2h43uagoYELWr/6xw/ZWjs6cn3CAy1W+KSjuki/OxRCQnSMf1d",
	"/xKFWKns8wJsP6fqn57QHtX4KeMaGR1bnWGPmniBCThOM6UTsHRMs4wz2qN2lTpexmou53S9Xjtikypp",
	"0CvzCtivwOJnWLlfsZIWpXV/QpoKHoPlSkYfjZJurRLzjcYZHdNfRJWhUfhqojdaK32eCwkiGZpY89Qx",
	"o2N6ptWSM9RkBlwgI0oTjTbTEhkBSbhcguCMaDSZsAO67tHXSs4Ej+3T6TghGlMBqx7hDJNUWZTxqudU",
	"NRYskjjXiKg4zrRG5vX0bJ9QSUnQ7SHFkXolvlN6yhlD+XSKXC6QxCAEasINgcwuUFonCxmZZpYIiG8N",
	"sQskBXKJ22AFJijDEZ/BSihgl0q9Az3Hp9Vdh+AieBcjMuNQqFLUXl7fpBjzGY+J4V+QCJ7woPEF6iWP",
	"8UrCEriAqcCnhWfuSBPUIAxTlMzB1J1BVmnllb1U6j3IVZ5FzNNp+ptMWXBxEyvpI8Up6J1INEK8yCPn",
	"SjrUKM2/uKz2ZG6skMqVdFoqiX3LEwfnFKZccLsiPh2FHSFj5RqnWsVojPPxG4fm1f8GtEuuBFgM8ZWA",
	"hLmPOsMlGuPcbjXEDrLrolCEzK/U7Wun7F1QljHumIM40w77lrsCMQNhsEfT2lIwEbg0b6TV3ua8yEyV",
	"EgiStrW9pwncvUM5tws6fj4cblSlHuVsj+JVVMYGv9HRsEcTLsvfmzWvXi+vqefsGTXV7LXsuikZqelH",
	"jG2Z30/QAhcH+4xhzVWVSYlD0Lz7my46hY6vLas8/4pbnfZBQ0qAHWYKFkVuJ4JzT7V1DQw61brjxnI5",
	"d9g8x1glCcoQeQfqOFXqNrhtJ6Y0gtlA6dGzA1GVCyzZdVn3AT87wy6y+RzNI4w6NKgeFS2PdogjdHmI",
	"XcLcq8stJqbFZg8uCdydBsoX5VfQGla0RzPJP2WYf3atb/sYOuM6N6ipYNcB/aDnIPkX9DXrwMNpNAEd",
	"CRG4WF2qW5TmHBPg0lnrfMMlT7KEjqsD5NLiHLX3hZJ2cTBdyyedoh/k3atZss1HeSdxcFyy1SZ2O9Hr",
	"IqqJo235pl7NGiAaHbVhtO4VRfp7MIswn1mL2tXV319Dfzbsv7y5f/5s/U1Xuijq6Y+oTR6IsZLOEfSj",
	"yrQE0Ve5i/rLURcHzJPcV4uTb0dHe0SKA4U7RI//D5DgUwuv1bKdSdnPBl25a3sWroRsHlTz1AsRvQDJ",
	"1ql0+KoA5PaYeFRBBQliZbipQaph9oudx/Ff4BkfLLn7B9+Wst3AyvFmJMp2Tdxf6mY5bQg72hT2qcjr",
	"29g2i8DhyG1H9TZZl7Cj5O0CeAXnNohyTbYfcKf/Cz91Id0pfBi4O5qQPfJLWLinKF2Nu6Yp6lDCUwGx",
	"i9o8x0Je4nHpZq4etSrlsS9uyp2Osgusd5oPpI28a/Cbuqz+UfEYL9A4xz6u7rkSgbJeNDZMNoH/XjBr",
	"6V+R9tqSdplzyeNbPNSaBO5c8/GeC8ENxkoyUzOp1r/ooq3YZ6tBaya2YT0DG8bxrkg7xGEOGbcod89R",
	"dVcGkoes6HW6oWbIpuu90nGmuV1duAwQvDlJ04m1aOzEGOfjgI/mvP8KDD5/1kfp5jxGJmlKAg2BgojM",
	"lPZXADFIJXkMorwhmHLJuJwPaG+fm+ZKjSoZpfwt+hRaKvsWV8HzTUXPcc6NRd1U8hZXhDOUls846j31",
	"eIurcNv9sBIflIxxU4kfykucBQiBco5kCSLDPQUHrtvkntdLQlP2O/UZdQwGydXV6QmZqkwywqVV/mzK",
	"09pTlcat/8P6XPIEjYUk7TiQ716T4+PjlzWg2GL3nkpU3Dt0OMElCpUmKO0ktnxZTut7MD7BZb9G1MG9",
	"O1X58ukHLATt2eeEC2vTcF3G5UxtOuN1GRqTNK0udsu7XlMG0T///Md//P0v//rDn/79178Vl2r9ySmZ",
	"h8eSAblcIJmjdITISJpNBY/LyzYCwijCZSwyll/MmQW4oDgTYF2umpydDsomdEx/HUYH8j6/vpucksnZ",
	"Ke3RZVEx6GgwHAydT1SKElJOx/R4MBoMXVEEu/CpJFogCLv4Qsf36x6NNAJbFT+Wowh4VJka5ePKoBhX",
	"osbDUKpCkSsJTpmLrHxvrq+XXb1tXXd3O9WWqP32tb4p+6tX+Wj4VS5Q21Pqupnny5mkZvDRcPgTiN92",
	"hZ/fK/s7fEvUjLiOjYBkxI0axFQ9mb9wfjYcPSS3NCRq3KN7ouPdRNWLkad4uZuifJBzBKM9RLSfdxzd",
	"0dE+9mzesnvaPZRsv3mse/Tb4R4ya2+inmQP8zregvyBzyATdjd5eDes9wc+mLo6g+ubzSLcWMtrYmOt",
	"Vq8a67W6cX3jYjFML9e0iu/JKb1ZV/mjGKGKFZdGrdIYSeWKe1xOjsUGLycqC/Hmp1tc1RYZLqPa06CJ",
	"INQHrLY0PlsN0rg9Dal5aouWrnxEeU+3Ja291gi2SGr1mvN/m+C6RpK9ktzoJ1Ehr82dac4slLZ9wZcu",
	"0XE5F9jPDJLf4vRCOSpiPfHg5xkxJksS0CtnKUu4JSBb798mmzp/TFETqwj4f2tIXIYgHp0kR+eAbkZf",
	"GXjdeI7uy2llHRmrERLnuHloktovnYwrX1s0Lrnx84IDrSGgkYS9U3SdKmEqLpuDvpc4SFhoeMJJEW6I",
	"xCVqAnGMqQ1kQK7O3zkrmqF14fXaK7R8x+h6mapfrI9jj/+nl5tWFIxCFDQ9VOExS+caGJbWfRVkdnWy",
	"bQRd5YLzYSHgI9XKqlgJ8pnbBYF6CIX2t4yfLQBKNV9CvIry24Faqiy+MKjn9VQrlsXWREXrC9x99Ebp",
	"ZXFgG//W42jC0WZa5P24GUcRpHxQtJu2GgAGses4Nico16Czaq5osBtH0ejol64XHozGL4YvhrRWt4rr",
	"Jlq02Z59vpbX6PpSrrKpr4U4L24vy+U3tarTZOH91+CQpqIhpjiO+p5Tur5Z/ycAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
