// Package journalhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package journalhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganizeRequestContractVersion.
const (
	JournalOrganizeV1 OrganizeRequestContractVersion = "journal-organize-v1"
)

// Valid indicates whether the value is a known member of the OrganizeRequestContractVersion enum.
func (e OrganizeRequestContractVersion) Valid() bool {
	switch e {
	case JournalOrganizeV1:
		return true
	default:
		return false
	}
}

// Defines values for TagType.
const (
	Event        TagType = "event"
	Mood         TagType = "mood"
	Organization TagType = "organization"
	Other        TagType = "other"
	Person       TagType = "person"
	Place        TagType = "place"
	Topic        TagType = "topic"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case Event:
		return true
	case Mood:
		return true
	case Organization:
		return true
	case Other:
		return true
	case Person:
		return true
	case Place:
		return true
	case Topic:
		return true
	default:
		return false
	}
}

// BookContext defines model for BookContext.
type BookContext struct {
	ContainsEntry bool               `json:"containsEntry"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestID"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ExistingBookRecommendation defines model for ExistingBookRecommendation.
type ExistingBookRecommendation struct {
	BookID openapi_types.UUID `json:"bookID"`
	Reason string             `json:"reason"`
}

// IllustrationSuggestion defines model for IllustrationSuggestion.
type IllustrationSuggestion struct {
	Composition  string   `json:"composition"`
	Reason       string   `json:"reason"`
	Setting      string   `json:"setting"`
	SourceQuotes []string `json:"sourceQuotes"`
	Style        string   `json:"style"`
	Subject      string   `json:"subject"`
	Summary      string   `json:"summary"`
}

// NewBookSuggestion defines model for NewBookSuggestion.
type NewBookSuggestion struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Reason      string   `json:"reason"`
	RelatedTags []string `json:"relatedTags"`
}

// OrganizeQuota defines model for OrganizeQuota.
type OrganizeQuota struct {
	Available              bool `json:"available"`
	DailyTokensRemaining   int  `json:"dailyTokensRemaining"`
	MonthlyTokensRemaining int  `json:"monthlyTokensRemaining"`
}

// OrganizeRequest defines model for OrganizeRequest.
type OrganizeRequest struct {
	Body                           string                         `json:"body"`
	Books                          []BookContext                  `json:"books"`
	ContentHash                    string                         `json:"contentHash"`
	ContractVersion                OrganizeRequestContractVersion `json:"contractVersion"`
	ExistingTags                   []string                       `json:"existingTags"`
	IllustrationSuggestionsEnabled bool                           `json:"illustrationSuggestionsEnabled"`
	RejectedTagNames               []string                       `json:"rejectedTagNames"`
	RequestID                      openapi_types.UUID             `json:"requestID"`
	Title                          string                         `json:"title"`
}

// OrganizeRequestContractVersion defines model for OrganizeRequest.ContractVersion.
type OrganizeRequestContractVersion string

// OrganizeResponse defines model for OrganizeResponse.
type OrganizeResponse struct {
	AnalysisVersion             string                       `json:"analysisVersion"`
	ContentHash                 string                       `json:"contentHash"`
	ExistingBookRecommendations []ExistingBookRecommendation `json:"existingBookRecommendations"`
	IllustrationSuggestion      *IllustrationSuggestion      `json:"illustrationSuggestion,omitempty"`
	NewBookSuggestions          []NewBookSuggestion          `json:"newBookSuggestions"`
	Quota                       OrganizeQuota                `json:"quota"`
	RequestID                   openapi_types.UUID           `json:"requestID"`
	Tags                        []Tag                        `json:"tags"`
}

// Tag defines model for Tag.
type Tag struct {
	Name string  `json:"name"`
	Type TagType `json:"type"`
}

// TagType defines model for Tag.Type.
type TagType string

// VoiceSessionRequest defines model for VoiceSessionRequest.
type VoiceSessionRequest struct {
	ConsentVersion string             `json:"consentVersion"`
	SessionID      openapi_types.UUID `json:"sessionID"`
}

// VoiceSessionTicket defines model for VoiceSessionTicket.
type VoiceSessionTicket struct {
	MaximumMilliseconds   int                `json:"maximumMilliseconds"`
	RemainingMilliseconds int                `json:"remainingMilliseconds"`
	ResetsAt              time.Time          `json:"resetsAt"`
	SessionID             openapi_types.UUID `json:"sessionID"`
	Token                 string             `json:"token"`
}

// WritingStyleCatalog defines model for WritingStyleCatalog.
type WritingStyleCatalog struct {
	DefaultStyle string                 `json:"defaultStyle"`
	Styles       []WritingStyleMetadata `json:"styles"`
	Version      string                 `json:"version"`
}

// WritingStyleMetadata defines model for WritingStyleMetadata.
type WritingStyleMetadata struct {
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
	Example     string `json:"example"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Order       int    `json:"order"`
}

// RequestIDHeader defines model for RequestIDHeader.
type RequestIDHeader = openapi_types.UUID

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// OrganizeJournalParams defines parameters for OrganizeJournal.
type OrganizeJournalParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// CreateJournalVoiceSessionParams defines parameters for CreateJournalVoiceSession.
type CreateJournalVoiceSessionParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// GetJournalWritingStylesParams defines parameters for GetJournalWritingStyles.
type GetJournalWritingStylesParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// OrganizeJournalJSONRequestBody defines body for OrganizeJournal for application/json ContentType.
type OrganizeJournalJSONRequestBody = OrganizeRequest

// CreateJournalVoiceSessionJSONRequestBody defines body for CreateJournalVoiceSession for application/json ContentType.
type CreateJournalVoiceSessionJSONRequestBody = VoiceSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(c *gin.Context, params OrganizeJournalParams)
	// CreateJournalVoiceSession Admit an authenticated subscriber to a resumable voice session.
	// (POST /v1/journal/voice/sessions)
	CreateJournalVoiceSession(c *gin.Context, params CreateJournalVoiceSessionParams)
	// StreamJournalVoiceSession Upgrade to the voice protocol with a single-use bearer ticket.
	// (GET /v1/journal/voice/sessions/{sessionID}/stream)
	StreamJournalVoiceSession(c *gin.Context, sessionID openapi_types.UUID)
	// GetJournalWritingStyles Public writing style metadata. No prompts or provider settings.
	// (GET /v1/journal/writing-styles)
	GetJournalWritingStyles(c *gin.Context, params GetJournalWritingStylesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// OrganizeJournal operation middleware
func (siw *ServerInterfaceWrapper) OrganizeJournal(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params OrganizeJournalParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OrganizeJournal(c, params)
}

// CreateJournalVoiceSession operation middleware
func (siw *ServerInterfaceWrapper) CreateJournalVoiceSession(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateJournalVoiceSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateJournalVoiceSession(c, params)
}

// StreamJournalVoiceSession operation middleware
func (siw *ServerInterfaceWrapper) StreamJournalVoiceSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "sessionID" -------------
	var sessionID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionID", c.Param("sessionID"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionID: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamJournalVoiceSession(c, sessionID)
}

// GetJournalWritingStyles operation middleware
func (siw *ServerInterfaceWrapper) GetJournalWritingStyles(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJournalWritingStylesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for If-None-Match, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter If-None-Match: %w", err), http.StatusBadRequest)
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJournalWritingStyles(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/journal/writing-styles", wrapper.GetJournalWritingStyles)
	router.POST(options.BaseURL+"/v1/journal/voice/sessions", wrapper.CreateJournalVoiceSession)
	router.GET(options.BaseURL+"/v1/journal/voice/sessions/:sessionID/stream", wrapper.StreamJournalVoiceSession)
	router.POST(options.BaseURL+"/v1/ai/operations/journal.organize/responses", wrapper.OrganizeJournal)
}

type BadGatewayJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type OrganizeJournalRequestObject struct {
	Params OrganizeJournalParams
	Body   *OrganizeJournalJSONRequestBody
}

type OrganizeJournalResponseObject interface {
	VisitOrganizeJournalResponse(w http.ResponseWriter) error
}

type OrganizeJournal200JSONResponse OrganizeResponse

func (response OrganizeJournal200JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OrganizeJournal401JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal403JSONResponse struct{ ForbiddenJSONResponse }

func (response OrganizeJournal403JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal409JSONResponse struct{ ConflictJSONResponse }

func (response OrganizeJournal409JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response OrganizeJournal413JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response OrganizeJournal422JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response OrganizeJournal429JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal502JSONResponse struct{ BadGatewayJSONResponse }

func (response OrganizeJournal502JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournal503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response OrganizeJournal503JSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type OrganizeJournaldefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response OrganizeJournaldefaultJSONResponse) VisitOrganizeJournalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJournalVoiceSessionRequestObject struct {
	Params CreateJournalVoiceSessionParams
	Body   *CreateJournalVoiceSessionJSONRequestBody
}

type CreateJournalVoiceSessionResponseObject interface {
	VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error
}

type CreateJournalVoiceSession201JSONResponse VoiceSessionTicket

func (response CreateJournalVoiceSession201JSONResponse) VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateJournalVoiceSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateJournalVoiceSessiondefaultJSONResponse) VisitCreateJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamJournalVoiceSessionRequestObject struct {
	SessionID openapi_types.UUID `json:"sessionID"`
}

type StreamJournalVoiceSessionResponseObject interface {
	VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error
}

type StreamJournalVoiceSession101Response struct {
}

func (response StreamJournalVoiceSession101Response) VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type StreamJournalVoiceSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response StreamJournalVoiceSessiondefaultJSONResponse) VisitStreamJournalVoiceSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetJournalWritingStylesRequestObject struct {
	Params GetJournalWritingStylesParams
}

type GetJournalWritingStylesResponseObject interface {
	VisitGetJournalWritingStylesResponse(w http.ResponseWriter) error
}

type GetJournalWritingStyles200ResponseHeaders struct {
	CacheControl string
	ETag         string
}

type GetJournalWritingStyles200JSONResponse struct {
	Body    WritingStyleCatalog
	Headers GetJournalWritingStyles200ResponseHeaders
}

func (response GetJournalWritingStyles200JSONResponse) VisitGetJournalWritingStylesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJournalWritingStyles304ResponseHeaders struct {
	CacheControl string
	ETag         string
}

type GetJournalWritingStyles304Response struct {
	Headers GetJournalWritingStyles304ResponseHeaders
}

func (response GetJournalWritingStyles304Response) VisitGetJournalWritingStylesResponse(w http.ResponseWriter) error {
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(304)
	return nil
}

type GetJournalWritingStylesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetJournalWritingStylesdefaultJSONResponse) VisitGetJournalWritingStylesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /v1/ai/operations/journal.organize/responses)
	OrganizeJournal(ctx context.Context, request OrganizeJournalRequestObject) (OrganizeJournalResponseObject, error)
	// CreateJournalVoiceSession Admit an authenticated subscriber to a resumable voice session.
	// (POST /v1/journal/voice/sessions)
	CreateJournalVoiceSession(ctx context.Context, request CreateJournalVoiceSessionRequestObject) (CreateJournalVoiceSessionResponseObject, error)
	// StreamJournalVoiceSession Upgrade to the voice protocol with a single-use bearer ticket.
	// (GET /v1/journal/voice/sessions/{sessionID}/stream)
	StreamJournalVoiceSession(ctx context.Context, request StreamJournalVoiceSessionRequestObject) (StreamJournalVoiceSessionResponseObject, error)
	// GetJournalWritingStyles Public writing style metadata. No prompts or provider settings.
	// (GET /v1/journal/writing-styles)
	GetJournalWritingStyles(ctx context.Context, request GetJournalWritingStylesRequestObject) (GetJournalWritingStylesResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// OrganizeJournal operation middleware
func (sh *strictHandler) OrganizeJournal(ctx *gin.Context, params OrganizeJournalParams) {
	var request OrganizeJournalRequestObject

	request.Params = params

	var body OrganizeJournalJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizeJournal(ctx, request.(OrganizeJournalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizeJournal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(OrganizeJournalResponseObject); ok {
		if err := validResponse.VisitOrganizeJournalResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateJournalVoiceSession operation middleware
func (sh *strictHandler) CreateJournalVoiceSession(ctx *gin.Context, params CreateJournalVoiceSessionParams) {
	var request CreateJournalVoiceSessionRequestObject

	request.Params = params

	var body CreateJournalVoiceSessionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJournalVoiceSession(ctx, request.(CreateJournalVoiceSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJournalVoiceSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateJournalVoiceSessionResponseObject); ok {
		if err := validResponse.VisitCreateJournalVoiceSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamJournalVoiceSession operation middleware
func (sh *strictHandler) StreamJournalVoiceSession(ctx *gin.Context, sessionID openapi_types.UUID) {
	var request StreamJournalVoiceSessionRequestObject

	request.SessionID = sessionID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StreamJournalVoiceSession(ctx, request.(StreamJournalVoiceSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamJournalVoiceSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StreamJournalVoiceSessionResponseObject); ok {
		if err := validResponse.VisitStreamJournalVoiceSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJournalWritingStyles operation middleware
func (sh *strictHandler) GetJournalWritingStyles(ctx *gin.Context, params GetJournalWritingStylesParams) {
	var request GetJournalWritingStylesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetJournalWritingStyles(ctx, request.(GetJournalWritingStylesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJournalWritingStyles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetJournalWritingStylesResponseObject); ok {
		if err := validResponse.VisitGetJournalWritingStylesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Frdchu39X8VDP65JLmU5OTv8I6RnYSN7aiSnHRGo84cYg9JWLvAGsDSojV8gLZXfYM+Qacv0LdpO32M",
	"Dj72k8sv2VHaOxILHPzO9zkAHiiTaSYFCqPp6IFmoCBFg8r9u8T3OWozefE9QozKDnFBR3Th//aogBTp",
	"iP6uf41JspL5hwWYfljVn7ygParwfc4VxnRkVI49qtkCU7CUZlKlYOiI5jmPaY+aVWZpaaO4mNP1em0X",
	"60wKjQ7MNxB/BwY/wMr+Y1IYFMb+hCxLOAPDpYjeaSnsWLXNFwpndET/L6oYjfxXHb1USqrLsInfMkbN",
	"FM8sMTqiF0oueYyKzIAnGBOpiEKTK4ExAUG4WELCY6JQ54kZ0HWPnksxSzgzT4dxTBRmCax6hMeYZtKg",
	"YKuehaoNGCQsICKSsVwpjB1OR/YJQQqCdg4pVOpAfCvVlMcxiqcDcr1AwiBJUBGuCeRmgcLYvTAm09yQ",
	"BNidJmaBpLBcYieYBFMUXsUXsEokxNdSvgI1x6fFrrxzEbxniLG2VigzVG6/vs6Q8RlnRPOPSBKeco/4",
	"CtWSM3wrYAk8gWmCT2ueQZDawyAxZihia6ZWB3mFyoG9lvI1iFWIIvrpkP42lwas3zApnKdYgE6IRCGw",
	"RfCct8JajVT8o41qTybGylK5FBalFNg3PLXmnMGUJ9ysiAtHfoaPWAFxpiRDra2MX1prXv06RrvkMgGD",
	"3r9SEDB3Xqe5QK2t2I0CZk12XSQKH/mlvDu3YO892DjmljgkF8ravuE2Qcwg0dijWW3Iswhc6JfCKMdz",
	"SDJTKRMEQdtoH2gK969QzM2Cjr4aDjeyUo/y+IDkVWTGBr2T02GPplyU/zdzXj1f3lBH2RFqwuy1+Lot",
	"CcnpO2SmjO8v0ABPjpZZjDVRVSyl1oLm3d9UUSl0fG1x5ehX1OprtzJSGthxrGCR5PZacJBUG6sn0Anr",
	"nmvDxdza5iUymaYovOcdiXEq5Z0X216bUgh6w0pPnx1pVWHDklwXd5MkybXxWeUqn89RP4IzJ2vNOzzr",
	"y07PeiR7ParRWFUctImWuWJoQ70HyQ2musvx9+yZwv3ELz1zc8OfaiooBSvao7ng73MMn20NbEGYVdIZ",
	"HTbh5l4nHaztE0qepuCD3qfEoIJMBaWSd6+h4oKtlox32tkb/GAd6NEmdmzwflRU/gTLVGjzXXwN863G",
	"9uwYW3t+gHm1FNiZPwJDTYBdCvpRzUHwj06ZcKRyGsVmR+IFnqyu5R0KfYkpcFG4MBc8zVM6qhTIhcE5",
	"KicLKczi6HUtmXRuvZV2r8bJLhmFivXo+B+vNm2303pt5G7a0a68Vq+aGkZ0cto2o3WvKAa/B73w5wDG",
	"oLL12+9voD8b9r++ffjq2fqLrrRU1G0/odLBEZkUVhD0ncyVgKQvg4j6y5MuChiS6Wfzky9PTg8KxLwz",
	"z+mXwio77rZbhVbxzmfeQIpPC7hRZ+0tGFzfekCeablHtcmmcpuWUmzR82bc0mSHrAoj3iv63Y72qGoQ",
	"BCQrzXXNThtyeb5XX5/gJLi1Xjzco3fUnO2KpO3efGtBt2vDLWWgTaTtxH04F5s5vwH+dBP8+yL57CLb",
	"zFTHu0o79Oza6xr25OV9HlX5T9soA5LdBtMp/0JOXZ5jAR/nLB2V0gEBzQ88UBQ2Ed/QDJWvM7IEmA0T",
	"IRFAqENwicJWlEZmnLkMLK12pFlgve3aEqdCaeMmdXH9k+QMr1BbwT4uOds8hqKe2TqaD0f/IDNr19bl",
	"0l57p33sXHN2h8dyk8K9rZBe8yThGpkUsa6xVCuyVFH7HDJVo9Fj0+A+BuPPpmjv0wRmLeMOxf5Dhboo",
	"/ZJtXPQ6xVBjpEv0PytuffHKNjjnYCCR86M7lRnkibkqOr9Nsdgvh4egOqLXaCAGH/XasXO51XRbElyW",
	"AagBtQS2TywliE/q4Dbz5q5SDO8hzbbIk8edw0Vc2/ggVbjh2tM7bD+UK9AUtCrwm7JzfsByxc3qymrU",
	"C2OcZWNjUJux1lZEXibN89RvQONXz/oomIwxJuMsI34NgWIRmUnljlgZCCk4g6Q8gZ1yEXMxH9gCbP9N",
	"XgWjMqyM/4DOskqwP+DKO3MT6CXOuTaomiDvcEV4jMLwGUd1II4fcOVvE7eDeCMFw00QP5aH5AtIEhRz",
	"JEtIcjxwY091176X9Sqjufcr+QEVA43k7dvJCzKVuYgJF0Y63ZTaOhBK41Z1O55rnqI2kGYdCvn2nJyd",
	"nX1dMxRTzD4QREW9A8MLXGIisxSFGTPDl+Vp6AGEX+CyX1vUQb07+7lw6KICgnLkw8KFMZm/juBiJjeF",
	"cV66xjjLqouz8i5Nl070zz//8R9//8u//vCnf//1b8WlRX88IXN/GT0g1wskcxR2IcYky6cJZ+VlBoFE",
	"S8IFS/I4XHzoBVinuEjA2PQ3vpgMykZqRH/jW2byOlyPjCdkfDGhtUhOTwbDwdDFrAwFZJyO6NngZDC0",
	"dRaYhQsl0QIhMYuPdPSw7tFIIcSr4s/yJAIeVaxGoU0fFG161Lh4z6Svm8oFk9h6Vpgb8Lq9q7cDN93Z",
	"q5oStd8WrG/Lkv2bcCTyWS6o2qcz62ZAL/vqGsOnw+EvsP2uK9Jwb+fuSA2RM2KbAAIiJrZdJroq892F",
	"3rPhybZ9S0aixj2lW3S2f1F1I+9WfL1/RfngwS44OWCL9vW5XXd6egg/m7eYbu0BINt3yuse/XJ4wJ61",
	"NyduyQHsddy1r8uaav9y/y6jXh84Z+qqDG5uN5NwYyzkxMZYLV81xmt54+bW+qJviG9o5d/jCb1dV/Gj",
	"6MqLERtGjVQYCWmTOysPN4oJbp+oTMSbn+5wVRuMcRnVnl7oCHx+wGpK47NRILSd09g1hLZoadNHFNqE",
	"HWHtXCGYIqjVc85/bYDr6nIPCnInvwiEkJs7w5xeSGX6CV/aQMfFPMF+rpH8jNMraVcR4xYP/jc9prxx",
	"o+M45YaAaL0v0vnUymOKihhJwD0bS22EIM46SbDOAd30vtLxuu05eigb4HWkjUJIreDmvkhqvySJuXS5",
	"ReGSa9cvWKPVBBQSP3eKtlIlsWRlcdB3Ow7S2Bc8XlOEayJwiYoAY5gZvwzI28tXlouma105XAe5lqsY",
	"bS1T1Yv1Dv/xjwpvW15w4r2gKaHKHvNsriDGkrvPYpldlWzbgt6GjUOz4O0jU9JIJhPygZsFgboL+fK3",
	"9J8DDOiD79371blDsJam0r5DE0jUm329RWXtIn8ysy0U9l+DYVaXlaL2KeZz1mBdpzfbnga6d1+GBOkQ",
	"Jx3C/CIrV8+hg3gObIH9c1voS/fIZrtZbh69vAxHsoevsavOhs82zdU/aWQLjAug1i0DJ78+5k9zl4ZX",
	"XPjeqqmcNBw8DcgbaV0kzYwmUtmf/u1ueK6gd7pFpvgS2CoK57C1CqL4Eg63ylEZ58zoqOgIgduPDrxa",
	"Fk6x8ZrYrvERL1dJaFP1KIog44OiCzNVXzxgthDfPFiwfWtctdsNcqMoOjn9f9siDk5Gz4fPh7RWzhUH",
	"+7ToPh35MBZK1/pQgKzrYz79FfdO5fDLWjHWJOHk16CQZUljm0Id9TkTur5d/ycAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
