// Package platformhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package platformhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EntitlementStatusStatus.
const (
	Active EntitlementStatusStatus = "active"
)

// Valid indicates whether the value is a known member of the EntitlementStatusStatus enum.
func (e EntitlementStatusStatus) Valid() bool {
	switch e {
	case Active:
		return true
	default:
		return false
	}
}

// Defines values for OKStatusStatus.
const (
	OKStatusStatusOk OKStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the OKStatusStatus enum.
func (e OKStatusStatus) Valid() bool {
	switch e {
	case OKStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PrivacyConsentScope.
const (
	PrivacyConsentScopeAdult                  PrivacyConsentScope = "adult"
	PrivacyConsentScopeFreeManagedRecognition PrivacyConsentScope = "free_managed_recognition"
	PrivacyConsentScopeLifetimeByok           PrivacyConsentScope = "lifetime_byok"
	PrivacyConsentScopeManagedSubscription    PrivacyConsentScope = "managed_subscription"
	PrivacyConsentScopePrivacyAndTerms        PrivacyConsentScope = "privacy_and_terms"
	PrivacyConsentScopeSensitiveHealthAi      PrivacyConsentScope = "sensitive_health_ai"
)

// Valid indicates whether the value is a known member of the PrivacyConsentScope enum.
func (e PrivacyConsentScope) Valid() bool {
	switch e {
	case PrivacyConsentScopeAdult:
		return true
	case PrivacyConsentScopeFreeManagedRecognition:
		return true
	case PrivacyConsentScopeLifetimeByok:
		return true
	case PrivacyConsentScopeManagedSubscription:
		return true
	case PrivacyConsentScopePrivacyAndTerms:
		return true
	case PrivacyConsentScopeSensitiveHealthAi:
		return true
	default:
		return false
	}
}

// Defines values for QuotaSnapshotPlan.
const (
	QuotaSnapshotPlanFree                QuotaSnapshotPlan = "free"
	QuotaSnapshotPlanManagedSubscription QuotaSnapshotPlan = "managed_subscription"
)

// Valid indicates whether the value is a known member of the QuotaSnapshotPlan enum.
func (e QuotaSnapshotPlan) Valid() bool {
	switch e {
	case QuotaSnapshotPlanFree:
		return true
	case QuotaSnapshotPlanManagedSubscription:
		return true
	default:
		return false
	}
}

// Defines values for ServiceStatusStatus.
const (
	ServiceStatusStatusOk    ServiceStatusStatus = "ok"
	ServiceStatusStatusReady ServiceStatusStatus = "ready"
)

// Valid indicates whether the value is a known member of the ServiceStatusStatus enum.
func (e ServiceStatusStatus) Valid() bool {
	switch e {
	case ServiceStatusStatusOk:
		return true
	case ServiceStatusStatusReady:
		return true
	default:
		return false
	}
}

// AppStoreNotificationRequest defines model for AppStoreNotificationRequest.
type AppStoreNotificationRequest struct {
	SignedPayload string `json:"signedPayload"`
}

// AttestationChallenge defines model for AttestationChallenge.
type AttestationChallenge struct {
	Challenge string    `json:"challenge"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// AttestationChallengeRequest defines model for AttestationChallengeRequest.
type AttestationChallengeRequest struct {
	KeyID string `json:"keyID"`
}

// AttestationRegistrationRequest defines model for AttestationRegistrationRequest.
type AttestationRegistrationRequest struct {
	ActivationSecret string `json:"activationSecret"`
	Attestation      []byte `json:"attestation"`
	Build            string `json:"build"`
	Challenge        string `json:"challenge"`
	KeyID            string `json:"keyID"`
}

// AttestationRegistrationResponse defines model for AttestationRegistrationResponse.
type AttestationRegistrationResponse struct {
	DeviceID openapi_types.UUID `json:"deviceID"`
	KeyID    string             `json:"keyID"`
}

// EntitlementStatus defines model for EntitlementStatus.
type EntitlementStatus struct {
	ExpiresAt time.Time               `json:"expiresAt"`
	Status    EntitlementStatusStatus `json:"status"`
}

// EntitlementStatusStatus defines model for EntitlementStatus.Status.
type EntitlementStatusStatus string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestID"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ManagedAIProduct defines model for ManagedAIProduct.
type ManagedAIProduct struct {
	BillingPeriod     string `json:"billingPeriod"`
	DailyTokenLimit   int    `json:"dailyTokenLimit"`
	JobRetention      string `json:"jobRetention"`
	MediaRetention    string `json:"mediaRetention"`
	ModelDisclosure   string `json:"modelDisclosure"`
	MonthlyTokenLimit int    `json:"monthlyTokenLimit"`
	PrivacyChoicesURL string `json:"privacyChoicesURL"`
	PrivacyURL        string `json:"privacyURL"`
	ProductID         string `json:"productID"`
	Provider          string `json:"provider"`
	SupportURL        string `json:"supportURL"`
	TermsURL          string `json:"termsURL"`
}

// OKStatus defines model for OKStatus.
type OKStatus struct {
	Status OKStatusStatus `json:"status"`
}

// OKStatusStatus defines model for OKStatus.Status.
type OKStatusStatus string

// PrivacyConsent defines model for PrivacyConsent.
type PrivacyConsent struct {
	DocumentVersion string              `json:"documentVersion"`
	Granted         bool                `json:"granted"`
	Scope           PrivacyConsentScope `json:"scope"`
}

// PrivacyConsentScope defines model for PrivacyConsent.Scope.
type PrivacyConsentScope string

// PrivacyConsentRequest defines model for PrivacyConsentRequest.
type PrivacyConsentRequest struct {
	Consents []PrivacyConsent `json:"consents"`
}

// PrivacyConsentResponse defines model for PrivacyConsentResponse.
type PrivacyConsentResponse struct {
	Count      int       `json:"count"`
	RecordedAt time.Time `json:"recordedAt"`
}

// QuotaSnapshot defines model for QuotaSnapshot.
type QuotaSnapshot struct {
	DailyLimit     int               `json:"dailyLimit"`
	DailyResetAt   time.Time         `json:"dailyResetAt"`
	DailyUsed      int               `json:"dailyUsed"`
	MonthlyLimit   int               `json:"monthlyLimit"`
	MonthlyResetAt time.Time         `json:"monthlyResetAt"`
	MonthlyUsed    int               `json:"monthlyUsed"`
	Plan           QuotaSnapshotPlan `json:"plan"`

	// Recognition Optional free-recognition capability quota exposed by Health.
	Recognition *RecognitionQuotaSnapshot `json:"recognition,omitempty"`
}

// QuotaSnapshotPlan defines model for QuotaSnapshot.Plan.
type QuotaSnapshotPlan string

// RecognitionQuotaSnapshot defines model for RecognitionQuotaSnapshot.
type RecognitionQuotaSnapshot struct {
	Completed int       `json:"completed"`
	Remaining int       `json:"remaining"`
	Reserved  int       `json:"reserved"`
	ResetAt   time.Time `json:"resetAt"`
}

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus struct {
	Status ServiceStatusStatus `json:"status"`
}

// ServiceStatusStatus defines model for ServiceStatus.Status.
type ServiceStatusStatus string

// SubscriptionTransactionRequest defines model for SubscriptionTransactionRequest.
type SubscriptionTransactionRequest struct {
	SignedTransaction string `json:"signedTransaction"`
}

// DevelopmentActivationHeader defines model for DevelopmentActivationHeader.
type DevelopmentActivationHeader = string

// RequestIDHeader defines model for RequestIDHeader.
type RequestIDHeader = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// GetAIQuotaParams defines parameters for GetAIQuota.
type GetAIQuotaParams struct {
	// BusinessDayStartHour Optional local business-day boundary for capability counters.
	BusinessDayStartHour *int `form:"businessDayStartHour,omitempty" json:"businessDayStartHour,omitempty"`

	// TimeZoneIdentifier Optional IANA time zone for capability counters.
	TimeZoneIdentifier    *string         `form:"timeZoneIdentifier,omitempty" json:"timeZoneIdentifier,omitempty"`
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// ActivateDevelopmentEntitlementParams defines parameters for ActivateDevelopmentEntitlement.
type ActivateDevelopmentEntitlementParams struct {
	XTellyouwhatRequestID     RequestIDHeader             `json:"X-Tellyouwhat-Request-ID"`
	XTellyouwhatDevActivation DevelopmentActivationHeader `json:"X-Tellyouwhat-Dev-Activation"`
}

// SynchronizeSubscriptionTransactionParams defines parameters for SynchronizeSubscriptionTransaction.
type SynchronizeSubscriptionTransactionParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// RecordPrivacyConsentsParams defines parameters for RecordPrivacyConsents.
type RecordPrivacyConsentsParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// DeletePrivacyDataParams defines parameters for DeletePrivacyData.
type DeletePrivacyDataParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// ProcessAppStoreNotificationJSONRequestBody defines body for ProcessAppStoreNotification for application/json ContentType.
type ProcessAppStoreNotificationJSONRequestBody = AppStoreNotificationRequest

// IssueAttestationChallengeJSONRequestBody defines body for IssueAttestationChallenge for application/json ContentType.
type IssueAttestationChallengeJSONRequestBody = AttestationChallengeRequest

// RegisterAttestationKeyJSONRequestBody defines body for RegisterAttestationKey for application/json ContentType.
type RegisterAttestationKeyJSONRequestBody = AttestationRegistrationRequest

// SynchronizeSubscriptionTransactionJSONRequestBody defines body for SynchronizeSubscriptionTransaction for application/json ContentType.
type SynchronizeSubscriptionTransactionJSONRequestBody = SubscriptionTransactionRequest

// RecordPrivacyConsentsJSONRequestBody defines body for RecordPrivacyConsents for application/json ContentType.
type RecordPrivacyConsentsJSONRequestBody = PrivacyConsentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Process health check
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// GetReadiness Dependency readiness check
	// (GET /readyz)
	GetReadiness(c *gin.Context)
	// GetAIQuota Read the current managed-AI quota snapshot
	// (GET /v1/ai/quota)
	GetAIQuota(c *gin.Context, params GetAIQuotaParams)
	// ProcessAppStoreNotification Receive an App Store Server Notification V2
	// (POST /v1/app-store/notifications)
	ProcessAppStoreNotification(c *gin.Context)
	// IssueAttestationChallenge Issue a one-time App Attest challenge
	// (POST /v1/attest/challenges)
	IssueAttestationChallenge(c *gin.Context)
	// RegisterAttestationKey Register an App Attest key
	// (POST /v1/attest/keys)
	RegisterAttestationKey(c *gin.Context)
	// ActivateDevelopmentEntitlement Activate a development-only managed entitlement
	// (POST /v1/dev/entitlements/activate)
	ActivateDevelopmentEntitlement(c *gin.Context, params ActivateDevelopmentEntitlementParams)
	// SynchronizeSubscriptionTransaction Synchronize a locally verified StoreKit transaction
	// (POST /v1/entitlements/transactions)
	SynchronizeSubscriptionTransaction(c *gin.Context, params SynchronizeSubscriptionTransactionParams)
	// RecordPrivacyConsents Record the current privacy consent versions
	// (POST /v1/privacy/consents)
	RecordPrivacyConsents(c *gin.Context, params RecordPrivacyConsentsParams)
	// DeletePrivacyData Delete all managed service data for the caller
	// (DELETE /v1/privacy/data)
	DeletePrivacyData(c *gin.Context, params DeletePrivacyDataParams)
	// GetManagedAIProduct Describe the managed-AI subscription product
	// (GET /v1/products/managed-ai)
	GetManagedAIProduct(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GetAIQuota operation middleware
func (siw *ServerInterfaceWrapper) GetAIQuota(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAIQuotaParams

	// ------------- Optional query parameter "businessDayStartHour" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "businessDayStartHour", c.Request.URL.Query(), &params.BusinessDayStartHour, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter businessDayStartHour: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "timeZoneIdentifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeZoneIdentifier", c.Request.URL.Query(), &params.TimeZoneIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeZoneIdentifier: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAIQuota(c, params)
}

// ProcessAppStoreNotification operation middleware
func (siw *ServerInterfaceWrapper) ProcessAppStoreNotification(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessAppStoreNotification(c)
}

// IssueAttestationChallenge operation middleware
func (siw *ServerInterfaceWrapper) IssueAttestationChallenge(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IssueAttestationChallenge(c)
}

// RegisterAttestationKey operation middleware
func (siw *ServerInterfaceWrapper) RegisterAttestationKey(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAttestationKey(c)
}

// ActivateDevelopmentEntitlement operation middleware
func (siw *ServerInterfaceWrapper) ActivateDevelopmentEntitlement(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ActivateDevelopmentEntitlementParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Tellyouwhat-Dev-Activation" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Dev-Activation")]; found {
		var XTellyouwhatDevActivation DevelopmentActivationHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Dev-Activation, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Dev-Activation", valueList[0], &XTellyouwhatDevActivation, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Dev-Activation: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatDevActivation = XTellyouwhatDevActivation

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Dev-Activation is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ActivateDevelopmentEntitlement(c, params)
}

// SynchronizeSubscriptionTransaction operation middleware
func (siw *ServerInterfaceWrapper) SynchronizeSubscriptionTransaction(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SynchronizeSubscriptionTransactionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SynchronizeSubscriptionTransaction(c, params)
}

// RecordPrivacyConsents operation middleware
func (siw *ServerInterfaceWrapper) RecordPrivacyConsents(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RecordPrivacyConsentsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RecordPrivacyConsents(c, params)
}

// DeletePrivacyData operation middleware
func (siw *ServerInterfaceWrapper) DeletePrivacyData(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeletePrivacyDataParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePrivacyData(c, params)
}

// GetManagedAIProduct operation middleware
func (siw *ServerInterfaceWrapper) GetManagedAIProduct(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetManagedAIProduct(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.GET(options.BaseURL+"/v1/ai/quota", wrapper.GetAIQuota)
	router.POST(options.BaseURL+"/v1/app-store/notifications", wrapper.ProcessAppStoreNotification)
	router.POST(options.BaseURL+"/v1/attest/challenges", wrapper.IssueAttestationChallenge)
	router.POST(options.BaseURL+"/v1/attest/keys", wrapper.RegisterAttestationKey)
	router.POST(options.BaseURL+"/v1/dev/entitlements/activate", wrapper.ActivateDevelopmentEntitlement)
	router.POST(options.BaseURL+"/v1/entitlements/transactions", wrapper.SynchronizeSubscriptionTransaction)
	router.POST(options.BaseURL+"/v1/privacy/consents", wrapper.RecordPrivacyConsents)
	router.DELETE(options.BaseURL+"/v1/privacy/data", wrapper.DeletePrivacyData)
	router.GET(options.BaseURL+"/v1/products/managed-ai", wrapper.GetManagedAIProduct)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse ServiceStatus

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetHealthdefaultJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse ServiceStatus

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetReadinessdefaultJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuotaRequestObject struct {
	Params GetAIQuotaParams
}

type GetAIQuotaResponseObject interface {
	VisitGetAIQuotaResponse(w http.ResponseWriter) error
}

type GetAIQuota200JSONResponse QuotaSnapshot

func (response GetAIQuota200JSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuota401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAIQuota401JSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuota403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAIQuota403JSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuota409JSONResponse struct{ ConflictJSONResponse }

func (response GetAIQuota409JSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuota503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetAIQuota503JSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIQuotadefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetAIQuotadefaultJSONResponse) VisitGetAIQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotificationRequestObject struct {
	Body *ProcessAppStoreNotificationJSONRequestBody
}

type ProcessAppStoreNotificationResponseObject interface {
	VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error
}

type ProcessAppStoreNotification200JSONResponse OKStatus

func (response ProcessAppStoreNotification200JSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotification400JSONResponse struct{ BadRequestJSONResponse }

func (response ProcessAppStoreNotification400JSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotification404JSONResponse struct{ NotFoundJSONResponse }

func (response ProcessAppStoreNotification404JSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotification413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ProcessAppStoreNotification413JSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotification503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response ProcessAppStoreNotification503JSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessAppStoreNotificationdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ProcessAppStoreNotificationdefaultJSONResponse) VisitProcessAppStoreNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAttestationChallengeRequestObject struct {
	Body *IssueAttestationChallengeJSONRequestBody
}

type IssueAttestationChallengeResponseObject interface {
	VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error
}

type IssueAttestationChallenge201JSONResponse AttestationChallenge

func (response IssueAttestationChallenge201JSONResponse) VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAttestationChallenge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IssueAttestationChallenge401JSONResponse) VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAttestationChallenge422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response IssueAttestationChallenge422JSONResponse) VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAttestationChallenge503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response IssueAttestationChallenge503JSONResponse) VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAttestationChallengedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response IssueAttestationChallengedefaultJSONResponse) VisitIssueAttestationChallengeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKeyRequestObject struct {
	Body *RegisterAttestationKeyJSONRequestBody
}

type RegisterAttestationKeyResponseObject interface {
	VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error
}

type RegisterAttestationKey201JSONResponse AttestationRegistrationResponse

func (response RegisterAttestationKey201JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RegisterAttestationKey401JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKey409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterAttestationKey409JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKey413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response RegisterAttestationKey413JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKey422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response RegisterAttestationKey422JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKey503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response RegisterAttestationKey503JSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterAttestationKeydefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RegisterAttestationKeydefaultJSONResponse) VisitRegisterAttestationKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlementRequestObject struct {
	Params ActivateDevelopmentEntitlementParams
}

type ActivateDevelopmentEntitlementResponseObject interface {
	VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error
}

type ActivateDevelopmentEntitlement200JSONResponse EntitlementStatus

func (response ActivateDevelopmentEntitlement200JSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlement401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ActivateDevelopmentEntitlement401JSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlement403JSONResponse struct{ ForbiddenJSONResponse }

func (response ActivateDevelopmentEntitlement403JSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlement404JSONResponse struct{ NotFoundJSONResponse }

func (response ActivateDevelopmentEntitlement404JSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlement503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response ActivateDevelopmentEntitlement503JSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateDevelopmentEntitlementdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ActivateDevelopmentEntitlementdefaultJSONResponse) VisitActivateDevelopmentEntitlementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransactionRequestObject struct {
	Params SynchronizeSubscriptionTransactionParams
	Body   *SynchronizeSubscriptionTransactionJSONRequestBody
}

type SynchronizeSubscriptionTransactionResponseObject interface {
	VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error
}

type SynchronizeSubscriptionTransaction200JSONResponse EntitlementStatus

func (response SynchronizeSubscriptionTransaction200JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SynchronizeSubscriptionTransaction401JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction403JSONResponse struct{ ForbiddenJSONResponse }

func (response SynchronizeSubscriptionTransaction403JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction404JSONResponse struct{ NotFoundJSONResponse }

func (response SynchronizeSubscriptionTransaction404JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response SynchronizeSubscriptionTransaction413JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response SynchronizeSubscriptionTransaction422JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransaction503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response SynchronizeSubscriptionTransaction503JSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SynchronizeSubscriptionTransactiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response SynchronizeSubscriptionTransactiondefaultJSONResponse) VisitSynchronizeSubscriptionTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsentsRequestObject struct {
	Params RecordPrivacyConsentsParams
	Body   *RecordPrivacyConsentsJSONRequestBody
}

type RecordPrivacyConsentsResponseObject interface {
	VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error
}

type RecordPrivacyConsents200JSONResponse PrivacyConsentResponse

func (response RecordPrivacyConsents200JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RecordPrivacyConsents401JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsents409JSONResponse struct{ ConflictJSONResponse }

func (response RecordPrivacyConsents409JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsents413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response RecordPrivacyConsents413JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsents422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response RecordPrivacyConsents422JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsents503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response RecordPrivacyConsents503JSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPrivacyConsentsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RecordPrivacyConsentsdefaultJSONResponse) VisitRecordPrivacyConsentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePrivacyDataRequestObject struct {
	Params DeletePrivacyDataParams
}

type DeletePrivacyDataResponseObject interface {
	VisitDeletePrivacyDataResponse(w http.ResponseWriter) error
}

type DeletePrivacyData204Response struct {
}

func (response DeletePrivacyData204Response) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePrivacyData401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePrivacyData401JSONResponse) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePrivacyData409JSONResponse struct{ ConflictJSONResponse }

func (response DeletePrivacyData409JSONResponse) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePrivacyData413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response DeletePrivacyData413JSONResponse) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePrivacyData503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response DeletePrivacyData503JSONResponse) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePrivacyDatadefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeletePrivacyDatadefaultJSONResponse) VisitDeletePrivacyDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetManagedAIProductRequestObject struct {
}

type GetManagedAIProductResponseObject interface {
	VisitGetManagedAIProductResponse(w http.ResponseWriter) error
}

type GetManagedAIProduct200JSONResponse ManagedAIProduct

func (response GetManagedAIProduct200JSONResponse) VisitGetManagedAIProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetManagedAIProductdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetManagedAIProductdefaultJSONResponse) VisitGetManagedAIProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Process health check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReadiness Dependency readiness check
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// GetAIQuota Read the current managed-AI quota snapshot
	// (GET /v1/ai/quota)
	GetAIQuota(ctx context.Context, request GetAIQuotaRequestObject) (GetAIQuotaResponseObject, error)
	// ProcessAppStoreNotification Receive an App Store Server Notification V2
	// (POST /v1/app-store/notifications)
	ProcessAppStoreNotification(ctx context.Context, request ProcessAppStoreNotificationRequestObject) (ProcessAppStoreNotificationResponseObject, error)
	// IssueAttestationChallenge Issue a one-time App Attest challenge
	// (POST /v1/attest/challenges)
	IssueAttestationChallenge(ctx context.Context, request IssueAttestationChallengeRequestObject) (IssueAttestationChallengeResponseObject, error)
	// RegisterAttestationKey Register an App Attest key
	// (POST /v1/attest/keys)
	RegisterAttestationKey(ctx context.Context, request RegisterAttestationKeyRequestObject) (RegisterAttestationKeyResponseObject, error)
	// ActivateDevelopmentEntitlement Activate a development-only managed entitlement
	// (POST /v1/dev/entitlements/activate)
	ActivateDevelopmentEntitlement(ctx context.Context, request ActivateDevelopmentEntitlementRequestObject) (ActivateDevelopmentEntitlementResponseObject, error)
	// SynchronizeSubscriptionTransaction Synchronize a locally verified StoreKit transaction
	// (POST /v1/entitlements/transactions)
	SynchronizeSubscriptionTransaction(ctx context.Context, request SynchronizeSubscriptionTransactionRequestObject) (SynchronizeSubscriptionTransactionResponseObject, error)
	// RecordPrivacyConsents Record the current privacy consent versions
	// (POST /v1/privacy/consents)
	RecordPrivacyConsents(ctx context.Context, request RecordPrivacyConsentsRequestObject) (RecordPrivacyConsentsResponseObject, error)
	// DeletePrivacyData Delete all managed service data for the caller
	// (DELETE /v1/privacy/data)
	DeletePrivacyData(ctx context.Context, request DeletePrivacyDataRequestObject) (DeletePrivacyDataResponseObject, error)
	// GetManagedAIProduct Describe the managed-AI subscription product
	// (GET /v1/products/managed-ai)
	GetManagedAIProduct(ctx context.Context, request GetManagedAIProductRequestObject) (GetManagedAIProductResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx *gin.Context) {
	var request GetReadinessRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAIQuota operation middleware
func (sh *strictHandler) GetAIQuota(ctx *gin.Context, params GetAIQuotaParams) {
	var request GetAIQuotaRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAIQuota(ctx, request.(GetAIQuotaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAIQuota")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAIQuotaResponseObject); ok {
		if err := validResponse.VisitGetAIQuotaResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProcessAppStoreNotification operation middleware
func (sh *strictHandler) ProcessAppStoreNotification(ctx *gin.Context) {
	var request ProcessAppStoreNotificationRequestObject

	var body ProcessAppStoreNotificationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProcessAppStoreNotification(ctx, request.(ProcessAppStoreNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProcessAppStoreNotification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ProcessAppStoreNotificationResponseObject); ok {
		if err := validResponse.VisitProcessAppStoreNotificationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IssueAttestationChallenge operation middleware
func (sh *strictHandler) IssueAttestationChallenge(ctx *gin.Context) {
	var request IssueAttestationChallengeRequestObject

	var body IssueAttestationChallengeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.IssueAttestationChallenge(ctx, request.(IssueAttestationChallengeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IssueAttestationChallenge")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(IssueAttestationChallengeResponseObject); ok {
		if err := validResponse.VisitIssueAttestationChallengeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterAttestationKey operation middleware
func (sh *strictHandler) RegisterAttestationKey(ctx *gin.Context) {
	var request RegisterAttestationKeyRequestObject

	var body RegisterAttestationKeyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterAttestationKey(ctx, request.(RegisterAttestationKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterAttestationKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RegisterAttestationKeyResponseObject); ok {
		if err := validResponse.VisitRegisterAttestationKeyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ActivateDevelopmentEntitlement operation middleware
func (sh *strictHandler) ActivateDevelopmentEntitlement(ctx *gin.Context, params ActivateDevelopmentEntitlementParams) {
	var request ActivateDevelopmentEntitlementRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ActivateDevelopmentEntitlement(ctx, request.(ActivateDevelopmentEntitlementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ActivateDevelopmentEntitlement")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ActivateDevelopmentEntitlementResponseObject); ok {
		if err := validResponse.VisitActivateDevelopmentEntitlementResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SynchronizeSubscriptionTransaction operation middleware
func (sh *strictHandler) SynchronizeSubscriptionTransaction(ctx *gin.Context, params SynchronizeSubscriptionTransactionParams) {
	var request SynchronizeSubscriptionTransactionRequestObject

	request.Params = params

	var body SynchronizeSubscriptionTransactionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SynchronizeSubscriptionTransaction(ctx, request.(SynchronizeSubscriptionTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SynchronizeSubscriptionTransaction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SynchronizeSubscriptionTransactionResponseObject); ok {
		if err := validResponse.VisitSynchronizeSubscriptionTransactionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordPrivacyConsents operation middleware
func (sh *strictHandler) RecordPrivacyConsents(ctx *gin.Context, params RecordPrivacyConsentsParams) {
	var request RecordPrivacyConsentsRequestObject

	request.Params = params

	var body RecordPrivacyConsentsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RecordPrivacyConsents(ctx, request.(RecordPrivacyConsentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordPrivacyConsents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RecordPrivacyConsentsResponseObject); ok {
		if err := validResponse.VisitRecordPrivacyConsentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePrivacyData operation middleware
func (sh *strictHandler) DeletePrivacyData(ctx *gin.Context, params DeletePrivacyDataParams) {
	var request DeletePrivacyDataRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePrivacyData(ctx, request.(DeletePrivacyDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePrivacyData")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeletePrivacyDataResponseObject); ok {
		if err := validResponse.VisitDeletePrivacyDataResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetManagedAIProduct operation middleware
func (sh *strictHandler) GetManagedAIProduct(ctx *gin.Context) {
	var request GetManagedAIProductRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetManagedAIProduct(ctx, request.(GetManagedAIProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetManagedAIProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetManagedAIProductResponseObject); ok {
		if err := validResponse.VisitGetManagedAIProductResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtZc9s48v8qKPz/j7Tla6Zq9KaJMxttMhmvj9mtTblcLaIlYQwCDAAqYVL67lsAL1CiJMrxkdnZN4sk",
	"gEb3r+/2VxqrJFUSpTV0+JWmoCFBi9r/OscFCpUmKO0otnwBliv5BoGhdq+5pEM6L35GVEKCdEj/dXCN",
	"QuQq+zQHe3COi4NmKY2oxo8Z18jo0OoMI2riOSbgdku4fIdyZud0eBxRm6duN2M1lzO6XEb0Ej9maOz4",
	"fC8CylUH4/Oth0+VTsDSIc0yzuj68Uu32KRKGvSc+RlYubP7FStpUfo/IU0Fj/1tB38YJd2z5pj/1zil",
	"Q/p/g4brg+KtGbzWWunL8pDiSIYm1jz1rBvS6zkSXRxKUHrJIOGGJCAc+cgO6TKir5ScCh4/I10jojEV",
	"kEeEM0xSZVHGeUSUJsaCRRKXFBEVx5nWJZ1+22ckUhJ035BKjJ6IX5SecMZQPq8UYxACtZMdZHaO0rqz",
	"kJFJZomA+N4QW8raoZW4D6xAp4ae6vfK/qIyyZ4ZeiqzSAoOqkzHSJhCQ6SyBD9zY8lUaWLn3JTX86Re",
	"QC4UsGul3oGe4Qspy+cYkRkCkqgUtT/vwKQY8ymPieFfkAie8IK5V6gXPMYbCQvgAiYCn1eTSpmbggzC",
	"MEXJnEY5uGQNVZ7YG+kApDT/gs+IhlEDWq6kg4SSeGB54pCdwoQLbnOyAMFZ8cUUuCjV/kamWsVojLvD",
	"awfs/GVAseBKgMVC1RKQMPMKaLhEY5zNshpiB4ll5Se84R+l6ZVVGt8r69DjyQw8ATDG3SMQF9phzXLn",
	"L6YgDEY0DR59pYbPJLJSQfo4wMZ7fVhZfFt/riZ/YGwdo0fWorO/XMlXc6eQslC/PSiMw3VbqYsofk65",
	"RjOyLW/KwBbAoLsu1JwV7tX3Yg+TwD3m43N/N/hc3e2H45NoL0kUm+wg9BJn3Fj9DWiBOoi6wlijX74m",
	"BGhODJTqtYwVc18M6QQM/nhGo13SnGRcsM4j9sHEI/I3agEkvGdFbLTOor2EUlqN/aTC0Bnp4pI7QsiA",
	"Hf0uXO/ddY3XTUhwZcFmZk/C91bXiJr6nFhJh9+C4btVu1y4S6+99T5HC1zsa6cUw06wJs7PzLrf6Sqd",
	"2C0Rv3+zW7h240UeCCisouKdfq7k1CqtxQZdZP1a+LjR+EIrlsX7GqAJF4LL2QVqrlgBIUhSFx3Ri+Nf",
	"uwDDgIv8Wt2jfOeiq9Jg8CRL6PCo/p5LizPUbsEfanKJzmKV9qtDnozDjk8UQ3HOTSyUyfQGWChp5/uR",
	"lmq+gDh/NVc8RnNz+a6t8Zp3MaBc1PtrL5ZOQPq3C16mveuqmaWp0rbnQRZ10u8KK9hqKIxW4LAu7C4u",
	"B7dYF9SadFfw0GJncIku2bQ40qULv719kNVcN4Hqvq/56yLjoqTcGQq5r0IyFWfO/v+O2pTaEPjZ05Od",
	"Tn6mQVoM3fxEKYEgPaRilXrtQemU4gMFlgnbcPsOJLvzQqARFXyKzm3cTXLPkDKcvjPZpAm/IzrViHfV",
	"O42xmklevjIoDXfe5G6OIOz8DnjAsU2c9TRGa5xorrab6Q+LxuJisf+bW0zMLpO9ImlnhODzuFj5o5dU",
	"+aMRFGgNeYcvKk/uc7UHuaBYZQUWE/hcWMSCwOLv4y7r6GSpGbIHR//BBlFJQNf9/pEpC1cSUjNXe6uL",
	"M1A9rb3/9hIN2n0CJL/qxiDbfUBpG3uSU369N0Hlun4kpQJkqO9OWTep8m3UFU81+rxDGS6bT9sSXXM4",
	"jqaQsVEoxhU5te+7wuM1JnbBayNd+yqQi4tsH6ZrTIBLn5vt/tSgXvTbdC+crBmYivrgzJDS5oAuHpbl",
	"s290rxUIvTfRCCzv4Q02+9mrALzXGqRxmcu31W2CbR5Wuwk3WKfZeWCMM81tfuW0BqviU5G/joxxBBVn",
	"t2tcP/sU/wBd0o+MjNKUFGsIVIvKSi2SGKSSPAZRV8UmXDIuZ4c06tNcachovFbK32LuM+2K2LdV3tsm",
	"tEi/UbeJvMeccOZivilH3ZOOt5gXDZ7NRLxXMsZ1In6rC5dVeYEsQGTY8+Bi123nXoZpZvvsd+oT6hgM",
	"kpub8TmZqEwywqVVXja1tHqS0mp0babnmidoLCRph0B+eUVOT09/CoBiq697EtHs3kFDZzfxoX3Eld2d",
	"wnA5Veu3elVj/M319UVd2PU6AK1CdkRilSSoY4xIGeVG5KNzBBEB2ZTk6xo3R0PMHByCJznBBeqcBEQ7",
	"WDu++UoNHdLw1YUA64wzGV2MaUQXVQxPjw+PDo8ct1SKElJOh/T08PjwyEXeYOfeDAyKGPmL+3tWlALr",
	"vsaY0SH9G9o3/hO60rY8OTp6tGp729JvqLaXxX7CDdGZlN60+A+n4NKJDUfUNBeljpY5pMMPty6/SxLQ",
	"OR3Si/KEgicknmPsczKYGWdsK0bT2jXRW7fdwHuVrSy8RGC+G/CiXBwJ0XSF6m6Qgx5oJP4WnqU/HJ3u",
	"ZmdHc+txpXHetKt0xb7+MlkcD4APvMptE8xo7MMzrxLNuMKHbuqbTwarEwTLaM0dpEUQQIRyFqNqBx0w",
	"yAv7DDr3liPoc/l0BbWpTeTHDHXeGLJqk3PIryxo+0Zlzsw18KjZfxY1OdfJabQ1zNtC+3j0fuQtN/mi",
	"JO5Lrlv4byVxXDvhbmLpyHAYXM1BzubAfaZQFx9+PNtV4799QpVazSnWDZO6R0kyAzP0hh1k7mx10xLu",
	"ZNcyomdHx7uVpNWT9Yt6KGYziOBX/LR7RT3n8ZK63x2SOpOwGv21npXBWOtZECi1ngcBy4fbZcvYOANd",
	"xLGZ1iht1cY9GI0Lv01MhYJO4zMaB3bHyd8qjQMZdHaLmShV5AgrdjlNBZK///OKLFDXC4pRmBhNGNO6",
	"QGruPKDKrI8s2xat9GBdneWm1/CzYo/XKN/WxF620xWrM1w+obLWldgNAUQoDfIJDGGZhonIq8gCGVHa",
	"vwDhnWHzolTZo93YDqa5/JKz3UvqGRy34LiH+q1Ownw3LvsSY+QLZwk9Zj0wiDsVNQkBQn4/2aBGThMC",
	"TfKgH9QJVUuH2sgfG5Nh56DCE+F+y+hAL9wfPykp3SNBaj1FdXDnjnfsG9zSyUmfRevTOt8NcD16CDQM",
	"CkxuOC3QBdlggGAVuPeYb4FsVbUIdnAJ6JPjtWuC5OUg2zk6scGCrxR3HHZ1Xfr5lrBqzyDpoVb6z68o",
	"FWYrE99IYw/tYLgYBIOoZlCO2+DmEMlJfw6SCdREo820NOTs6Ix8mqP0cVvZUHbOJZhzNGj9aKyfLlkP",
	"l8oyEAblpGAa5lGSwh1Lto3FP2lmsz71s0HnWENhOD0csvU505k946m/TDqzsSa6mulUmCcQivZASZHX",
	"s6vYUoIOtQ7QYxq9bum0bZoSW3zgVS7juVaSf8ENnZVv18Lbp/GoOzpBz5z89NbnlQSXhN1Y71FjJae8",
	"/h+Q71Wx/1Iu+GVrI4GOEijKmSIvSxXIiizvLbfEtpS2t9Uo+yODcBBmU8AcK83akynmu7UP3cNBz2wW",
	"NozxbLINxWekmKEx5BNqJL6U9b/o+r+07OkE3Sp8lupYY6HsJ5pulS7xta7NDGxZ5BdYBPZtXT73z8vl",
	"5/AYLZj1cPmso9YqBHG0FQVAT8SfAdt/UXwWKCEgRBOvVP/N5oTYTJ8I4btL/SDqU0UzqGr8wLe1CNeG",
	"3Z/QXK+d1WGoL7KJ4HGV8PquU6oEj3OSoAXHlsNH78S68ycY/n/bwWjcDh3TmjudMihY7oSwrL/4WjUK",
	"6y9dxlw+q9q5waN6l+BZWGAIHrdCjdYWBRjCHcatX74Cvbxd/icAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
