// Package workerhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package workerhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ProcessJobRequestAppID.
const (
	Health ProcessJobRequestAppID = "health"
)

// Valid indicates whether the value is a known member of the ProcessJobRequestAppID enum.
func (e ProcessJobRequestAppID) Valid() bool {
	switch e {
	case Health:
		return true
	default:
		return false
	}
}

// Defines values for ServiceStatusStatus.
const (
	Ok ServiceStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ServiceStatusStatus enum.
func (e ServiceStatusStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ProcessJobRequest defines model for ProcessJobRequest.
type ProcessJobRequest struct {
	AppID ProcessJobRequestAppID `json:"appID"`
	JobID string                 `json:"jobID"`
}

// ProcessJobRequestAppID defines model for ProcessJobRequest.AppID.
type ProcessJobRequestAppID string

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus struct {
	Status ServiceStatusStatus `json:"status"`
}

// ServiceStatusStatus defines model for ServiceStatus.Status.
type ServiceStatusStatus string

// WorkerSecret defines model for WorkerSecret.
type WorkerSecret = string

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// ProcessJobParams defines parameters for ProcessJob.
type ProcessJobParams struct {
	XTellyouwhatWorkerSecret *WorkerSecret `json:"X-Tellyouwhat-Worker-Secret,omitempty"`
}

// ProcessJobJSONRequestBody defines body for ProcessJob for application/json ContentType.
type ProcessJobJSONRequestBody = ProcessJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	GetWorkerHealth(c *gin.Context)

	// (POST /internal/jobs/process)
	ProcessJob(c *gin.Context, params ProcessJobParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetWorkerHealth operation middleware
func (siw *ServerInterfaceWrapper) GetWorkerHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkerHealth(c)
}

// ProcessJob operation middleware
func (siw *ServerInterfaceWrapper) ProcessJob(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ProcessJobParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Tellyouwhat-Worker-Secret" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Worker-Secret")]; found {
		var XTellyouwhatWorkerSecret WorkerSecret
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Worker-Secret, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Worker-Secret", valueList[0], &XTellyouwhatWorkerSecret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Worker-Secret: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatWorkerSecret = &XTellyouwhatWorkerSecret

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessJob(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetWorkerHealth)
	router.POST(options.BaseURL+"/internal/jobs/process", wrapper.ProcessJob)
}

type BadGatewayJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type GetWorkerHealthRequestObject struct {
}

type GetWorkerHealthResponseObject interface {
	VisitGetWorkerHealthResponse(w http.ResponseWriter) error
}

type GetWorkerHealth200JSONResponse ServiceStatus

func (response GetWorkerHealth200JSONResponse) VisitGetWorkerHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWorkerHealthdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetWorkerHealthdefaultJSONResponse) VisitGetWorkerHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessJobRequestObject struct {
	Params ProcessJobParams
	Body   *ProcessJobJSONRequestBody
}

type ProcessJobResponseObject interface {
	VisitProcessJobResponse(w http.ResponseWriter) error
}

type ProcessJob204Response struct {
}

func (response ProcessJob204Response) VisitProcessJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ProcessJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ProcessJob401JSONResponse) VisitProcessJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessJob413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ProcessJob413JSONResponse) VisitProcessJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessJob422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ProcessJob422JSONResponse) VisitProcessJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessJob502JSONResponse struct{ BadGatewayJSONResponse }

func (response ProcessJob502JSONResponse) VisitProcessJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ProcessJobdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ProcessJobdefaultJSONResponse) VisitProcessJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /healthz)
	GetWorkerHealth(ctx context.Context, request GetWorkerHealthRequestObject) (GetWorkerHealthResponseObject, error)

	// (POST /internal/jobs/process)
	ProcessJob(ctx context.Context, request ProcessJobRequestObject) (ProcessJobResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetWorkerHealth operation middleware
func (sh *strictHandler) GetWorkerHealth(ctx *gin.Context) {
	var request GetWorkerHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkerHealth(ctx, request.(GetWorkerHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkerHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetWorkerHealthResponseObject); ok {
		if err := validResponse.VisitGetWorkerHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProcessJob operation middleware
func (sh *strictHandler) ProcessJob(ctx *gin.Context, params ProcessJobParams) {
	var request ProcessJobRequestObject

	request.Params = params

	var body ProcessJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProcessJob(ctx, request.(ProcessJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProcessJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ProcessJobResponseObject); ok {
		if err := validResponse.VisitProcessJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFZNb9s4EP0rxOweFct2WyDQrUWLrrs9GE0Wu0DgAy2OLSY0qZIjp26g/74YUvL3Ng02SG+mzJl5nHnv",
	"kQ9QulXtLFoKUDxALb1cIaGPq7+dv0N/haVH4rW2UECFUqGHDKxcIRTwz8U1GrNxzX0l6SKFXHQxGYSy",
	"wpXk4JX89hntkioo3ozGGay07dejDGhTc7JAXtsltG2bgcdQOxswQnkn1UdJeC83vCqdJbQRk6xro0tJ",
	"2tn8NjjL33ZFf/e4gAJ+y3fHzNO/If/gvfNfuiKppMJQel1zMijgukJx6+aidI1RwjoScxS1dyWGgGoA",
	"bQYxx8sh+oJfGwwkFlKbDsFUboyT6tq5z9Iv8WW74zs8c6c2Ar+ViCoIqlDcRxoIo1eaIsy/rGyocl5/",
	"R/WyGDsoITJS6CC0XUujVQerm6ecG/xgSdMv4JfHBXq0JR6ia3v1RAHEbO+RpDYRllKa00gz9a5GT5p1",
	"spAmYAb13ic+jIq0+KHgMlhxF5aP74zK/Npoz4O8Sdl30bPtfje/xZK2Itk24mngsRfYo53uenOMLyU4",
	"B2uaJv/JzTtZPRGarOvJ+4jRNisuVaE0VO3V2jX31s3T3j0XHI0vsye1OhXsk5070hX6tS7xiiQ14YnH",
	"Cdug/jzu7sxZjjB1UadgmL1YNl7T5orHhM91o3R1ZK3/xE2SlbYLx9kO5TWxhN5KI1jNXpYkmoBKzDfR",
	"oZbpNhHkWHLuDoVqPLuAeDthVYYB19JkuNgeHpHwiLfTCWSwRh9StdFgOBjyDFyNVtYaCng1GA2GkEEt",
	"qYqnzxNDvvPvZWoATyCay0RBAR+RUvo/EpWOLsHxcPhs7nRIlR97Z+eRbE++sVbbZTRPhQvZGPqvSlvo",
	"SZ8HlIDihikjl4FJ1GGBGW/JdTe3nKeQd7Xj48SFMz3byTi2evd+uTkPa7clP2BjO0vMxkDvnHq+a+DU",
	"ZtpDEZFvsD2Z9OtTQvf3xUJbHSpUIjQlp140xmziRF4PR49P4+Aq5qDRq8eDjp8ZHDce/0yx0wu2zeDN",
	"8Cdi9958/5ttx9ZzM2v3CPjJzQOzL8b4dU+fw/ZPvV5LwmgnUlv0wiKxQiCDxhs2MqK6yPOkmuJyeDmC",
	"vSoPvb/1dG+z7acIoJ21/wYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
