// Package lifecyclehttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package lifecyclehttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ChangeLifecycleStateParamsAction.
const (
	Pause  ChangeLifecycleStateParamsAction = "pause"
	Resume ChangeLifecycleStateParamsAction = "resume"
	Seal   ChangeLifecycleStateParamsAction = "seal"
	Serve  ChangeLifecycleStateParamsAction = "serve"
)

// Valid indicates whether the value is a known member of the ChangeLifecycleStateParamsAction enum.
func (e ChangeLifecycleStateParamsAction) Valid() bool {
	switch e {
	case Pause:
		return true
	case Resume:
		return true
	case Seal:
		return true
	case Serve:
		return true
	default:
		return false
	}
}

// Status defines model for Status.
type Status struct {
	Background        int    `json:"background"`
	BackgroundEnabled bool   `json:"backgroundEnabled"`
	BootID            string `json:"bootID"`
	HTTP              int    `json:"http"`
	HTTPEnabled       bool   `json:"httpEnabled"`
	Protocol          int    `json:"protocol"`
	Slot              string `json:"slot"`
}

// ChangeLifecycleStateJSONBody defines parameters for ChangeLifecycleState.
type ChangeLifecycleStateJSONBody struct {
	BootID string `json:"bootID"`
}

// ChangeLifecycleStateParamsAction defines parameters for ChangeLifecycleState.
type ChangeLifecycleStateParamsAction string

// ChangeLifecycleStateJSONRequestBody defines body for ChangeLifecycleState for application/json ContentType.
type ChangeLifecycleStateJSONRequestBody ChangeLifecycleStateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /control/{action})
	ChangeLifecycleState(c *gin.Context, action ChangeLifecycleStateParamsAction)

	// (GET /status)
	ReadLifecycleStatus(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ChangeLifecycleState operation middleware
func (siw *ServerInterfaceWrapper) ChangeLifecycleState(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "action" -------------
	var action ChangeLifecycleStateParamsAction

	err = runtime.BindStyledParameterWithOptions("simple", "action", c.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter action: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChangeLifecycleState(c, action)
}

// ReadLifecycleStatus operation middleware
func (siw *ServerInterfaceWrapper) ReadLifecycleStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReadLifecycleStatus(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/status", wrapper.ReadLifecycleStatus)
	router.POST(options.BaseURL+"/control/:action", wrapper.ChangeLifecycleState)
}

type ChangeLifecycleStateRequestObject struct {
	Action ChangeLifecycleStateParamsAction `json:"action"`
	Body   *ChangeLifecycleStateJSONRequestBody
}

type ChangeLifecycleStateResponseObject interface {
	VisitChangeLifecycleStateResponse(w http.ResponseWriter) error
}

type ChangeLifecycleState200JSONResponse Status

func (response ChangeLifecycleState200JSONResponse) VisitChangeLifecycleStateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeLifecycleState400Response struct {
}

func (response ChangeLifecycleState400Response) VisitChangeLifecycleStateResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ChangeLifecycleState409Response struct {
}

func (response ChangeLifecycleState409Response) VisitChangeLifecycleStateResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type ReadLifecycleStatusRequestObject struct {
}

type ReadLifecycleStatusResponseObject interface {
	VisitReadLifecycleStatusResponse(w http.ResponseWriter) error
}

type ReadLifecycleStatus200JSONResponse Status

func (response ReadLifecycleStatus200JSONResponse) VisitReadLifecycleStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /control/{action})
	ChangeLifecycleState(ctx context.Context, request ChangeLifecycleStateRequestObject) (ChangeLifecycleStateResponseObject, error)

	// (GET /status)
	ReadLifecycleStatus(ctx context.Context, request ReadLifecycleStatusRequestObject) (ReadLifecycleStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ChangeLifecycleState operation middleware
func (sh *strictHandler) ChangeLifecycleState(ctx *gin.Context, action ChangeLifecycleStateParamsAction) {
	var request ChangeLifecycleStateRequestObject

	request.Action = action

	var body ChangeLifecycleStateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangeLifecycleState(ctx, request.(ChangeLifecycleStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangeLifecycleState")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ChangeLifecycleStateResponseObject); ok {
		if err := validResponse.VisitChangeLifecycleStateResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReadLifecycleStatus operation middleware
func (sh *strictHandler) ReadLifecycleStatus(ctx *gin.Context) {
	var request ReadLifecycleStatusRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReadLifecycleStatus(ctx, request.(ReadLifecycleStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadLifecycleStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ReadLifecycleStatusResponseObject); ok {
		if err := validResponse.VisitReadLifecycleStatusResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFRRi+M2EP4rYnqPjp3sFcr67a4tdKGUpV0oZdmCIk0c3coaVRrnNgT/9zKys+d0U+g99SmONPq++Wa+",
	"mRMY6iMFDJyhPUE2e+x1+fyNNQ/lS1vr2FHQ/j5RxMQOM7Q77TNWEBdHJ9hq89wlGoKVf3yMCC24wNhh",
	"grFa3P8Y9NbjMmxL5FGHEkbEdz8s7jInFzqo4GXV0SroXg4/TlFjBXvmeIXwMvynh4f7c/C/s799c44d",
	"i1gmQ/66uOyJ3+Y8jhUk/GtwSfgev2C8ypxfXmZ2rVaz0OUVPFVnPtp+QsMwCqELO5JULGaTXJTuQQvf",
	"U2DtAqaVJ4oCoixGT8ceAytDgRP5Wv2CB0wKXyJltIr3iYZur3iPKg5b74yKiV6ONVTAjr1QP6D3f9Dw",
	"+16z8mS0V97t0ByNR/Xh/g4qOGDKUxKbel2vpVwUMejooIX39aZeQwVR877YqJlzaU7aSO6jHEbKpbzi",
	"Ny2nd1Y07XXo8OcznbgWC1TSPTKmDO3jCZwwCzxUMLd2QoZlczgNWM0zIEwYhl5aljEdsETmoZ/Qhyy/",
	"GbVfdOC1408TKmb+SPYoUCIIQ8lfx+idKQqaT1lqclpwfs2wvU5J1MyYROOfj3q1W69un07vb8Z3UP2n",
	"AfqHQ2fc6866rFY5yJFCnlK6Wa+/Su27hDto4Zvmyxpq5h3UzAuosF76uDRZmdJ5pc1zoM8ebYdWbY/F",
	"p/gS0TBacarBnGvx27dTbpdQd+GgvbNn86vJFYqSmhs4P719+/R+wp7zsPKGBs6sg3WhU58pPauY8CCi",
	"FCcdcmlsLYrGCpr8umA7vGLsX1HbC1sPGf6Xan+wvcsyvCqXuutg3widRMkOlFGZh25IHtqystqm2dx8",
	"J4Nfb9rN7fp2DePT+HcAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
