// Package albumhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package albumhttpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ManifestKind.
const (
	LivePhoto ManifestKind = "live_photo"
	Photo     ManifestKind = "photo"
	Video     ManifestKind = "video"
)

// Valid indicates whether the value is a known member of the ManifestKind enum.
func (e ManifestKind) Valid() bool {
	switch e {
	case LivePhoto:
		return true
	case Photo:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRole.
const (
	Adjustment    ResourceRole = "adjustment"
	Alternate     ResourceRole = "alternate"
	CurrentPhoto  ResourceRole = "current_photo"
	CurrentVideo  ResourceRole = "current_video"
	OriginalPhoto ResourceRole = "original_photo"
	OriginalVideo ResourceRole = "original_video"
	PairedVideo   ResourceRole = "paired_video"
)

// Valid indicates whether the value is a known member of the ResourceRole enum.
func (e ResourceRole) Valid() bool {
	switch e {
	case Adjustment:
		return true
	case Alternate:
		return true
	case CurrentPhoto:
		return true
	case CurrentVideo:
		return true
	case OriginalPhoto:
		return true
	case OriginalVideo:
		return true
	case PairedVideo:
		return true
	default:
		return false
	}
}

// Defines values for UploadState.
const (
	OriginalsVerified UploadState = "originals_verified"
	Queued            UploadState = "queued"
	Uploading         UploadState = "uploading"
	Verifying         UploadState = "verifying"
)

// Valid indicates whether the value is a known member of the UploadState enum.
func (e UploadState) Valid() bool {
	switch e {
	case OriginalsVerified:
		return true
	case Queued:
		return true
	case Uploading:
		return true
	case Verifying:
		return true
	default:
		return false
	}
}

// Grant defines model for Grant.
type Grant struct {
	ExpiresAt  time.Time         `json:"expiresAt"`
	Headers    map[string]string `json:"headers"`
	ResourceID string            `json:"resourceID"`
	Url        string            `json:"url"`
}

// Manifest defines model for Manifest.
type Manifest struct {
	AssetID        string       `json:"assetID"`
	Edited         bool         `json:"edited"`
	Kind           ManifestKind `json:"kind"`
	Resources      []Resource   `json:"resources"`
	SourceRevision string       `json:"sourceRevision"`
}

// ManifestKind defines model for Manifest.Kind.
type ManifestKind string

// Resource defines model for Resource.
type Resource struct {
	Id        string       `json:"id"`
	Role      ResourceRole `json:"role"`
	Sha256    string       `json:"sha256"`
	SizeBytes int64        `json:"sizeBytes"`
}

// ResourceRole defines model for Resource.Role.
type ResourceRole string

// Upload defines model for Upload.
type Upload struct {
	DerivedBudget  int64              `json:"derivedBudget"`
	ExpiresAt      time.Time          `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	Manifest       Manifest           `json:"manifest"`
	ManifestDigest string             `json:"manifestDigest"`
	OriginalBytes  int64              `json:"originalBytes"`
	RequestID      openapi_types.UUID `json:"requestID"`
	State          UploadState        `json:"state"`
}

// UploadState defines model for Upload.State.
type UploadState string

// UploadID defines model for UploadID.
type UploadID = openapi_types.UUID

// Error defines model for Error.
type Error struct {
	Code string `json:"code"`
}

// CreateAlbumUploadJSONBody defines parameters for CreateAlbumUpload.
type CreateAlbumUploadJSONBody struct {
	Manifest  Manifest           `json:"manifest"`
	RequestID openapi_types.UUID `json:"requestID"`
}

// CreateAlbumUploadJSONRequestBody defines body for CreateAlbumUpload for application/json ContentType.
type CreateAlbumUploadJSONRequestBody CreateAlbumUploadJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/albums/uploads)
	CreateAlbumUpload(c *gin.Context)

	// (GET /v1/albums/uploads/{id})
	GetAlbumUpload(c *gin.Context, id UploadID)

	// (POST /v1/albums/uploads/{id}/grants)
	AuthorizeAlbumUploadResources(c *gin.Context, id UploadID)

	// (POST /v1/albums/uploads/{id}/submit)
	SubmitAlbumUpload(c *gin.Context, id UploadID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateAlbumUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateAlbumUpload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAlbumUpload(c)
}

// GetAlbumUpload operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumUpload(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAlbumUpload(c, id)
}

// AuthorizeAlbumUploadResources operation middleware
func (siw *ServerInterfaceWrapper) AuthorizeAlbumUploadResources(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthorizeAlbumUploadResources(c, id)
}

// SubmitAlbumUpload operation middleware
func (siw *ServerInterfaceWrapper) SubmitAlbumUpload(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitAlbumUpload(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/albums/uploads", wrapper.CreateAlbumUpload)
	router.GET(options.BaseURL+"/v1/albums/uploads/:id", wrapper.GetAlbumUpload)
	router.POST(options.BaseURL+"/v1/albums/uploads/:id/grants", wrapper.AuthorizeAlbumUploadResources)
	router.POST(options.BaseURL+"/v1/albums/uploads/:id/submit", wrapper.SubmitAlbumUpload)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFjfb9s2EP5XCK7AXuQfSdsA9Z7ctSsCbECXYntY4AW0eLYuk0iWPLlRA//vA0lJliw1qbO1T7EkHnn3",
	"fd/9YO55qgujFShyfHHPjbCiAAIbnv4wuRby8o3/jYovuBGU8YQrUQBfcJQ84RY+lmhB8gXZEhLu0gwK",
	"4S022haC+IKXZVhJlfFWjiyqLd/v997YGa0chNPeWqut/5FqRaDI/xTG5JgKQq1mt04r/+5wgpAS/SeR",
	"v7fagCX0O21E7iDhpvPK7ynB/z12ohvAdVy1al3V61tIKboqwaUWjT+OL/iypAwU1a4lzKXaQMI+lppE",
	"whwJAqYtc2B3mAIDH9qUXSoCq0TOjNU7lGCZBBKYOyYsMKWJWaDSKpDT4FqMNPj/zooaka+PGe4MWnBL",
	"6rEhBcGEsIAhJQnPQMia/PGD7oc2R2AFVnVpU4jCGawvbd6Xh8URdfSJ6WwZNzi4mnTiXI1485tQuAF3",
	"KnjCOaAYgRHkeeML/vf1cvKXmHyeT17dTFb3Z8mri/2zMRxBInnP2/DXWucglP/2D6rwBVRZ+NhMpknz",
	"hHtF+L857uAmvlyNbN1AEbxEgiL8eGZhwxf8h9khn2e1fGZXtYW3LsTdZbR5fp7wAlX9dNaeJKwVlV8a",
	"ja5ghw5j5hXi7ldQW8r44vzlRTBvns8eY7DBc7BvDUiLWTfCMT7baE7jE+UTqbQ6hy5d2uIWlchvGt7a",
	"Fw2BRvig28e0tBYUteub5+a7kLelo8JXvISLPJQIglHuXSbOX14MA/lFTDbzyavV/cWL8SAcfobXFUUo",
	"2sxDRRcveOARCx/dgUVUBFuwAxpjzfeQdDdtPRsjLHaRE+mSYHEH8nUpt0AnO508pfZFhTzStXwGHerJ",
	"Q1nX1p2OzRvc1pZd/h4jrxHY0wiM/IGri9mj8YXm1RV8GfjzXxP+sYQy5OgOLG6q+LLxz92EtwhyRLyj",
	"Omod68A6QKtx6RiI5EgkDzcCHxmkpUWqPniGIpLLfF0WyzTVZeyu/S7/Zx2Ob+jrHJiIC5nodf/Y/CUj",
	"zSgDJvyWjnUmlylbGsOWROCIiVwrYOgYKlduNpgiKJryutmHVgHCgj1QkxGZOIOg2uihl7X7E/1JgWSy",
	"tMHXyJr3fItqO2VDkpjU4MLUUYBQzFjYIXxyfm7JdSpyZsHkIgVfmcKAYkHIyrtKSL4mRvRYzG+2fH8Z",
	"dRG7BZ9Pz6bzIF8DShjkC/58Op8+DwWSsgD/bHc2i3jNor9xCNUxR3w9CABeSr7gP1sQBOHIuqK0Anqt",
	"ZfWtBsenpPspCTcYdEZSYnwi7U/ex9P0+fzsJEgeiq3Ge2QOvgI/4oL0okEJhdH+tLyK2qlA1jrkwXIj",
	"yvyLQLbez+JFYB+OGypkdo9y7zepG0NfJe+AjiXSA2X+HUCpE2INuVY++drKcCgbIJti8jRkkt5N7Xrc",
	"7rBk1t7k9qsvgzrb+kvG4B540u5Jm719TN4Whiq21rKasnCXcSzVO7BMq7wK6DRq/9ExuBMpNaWLRc27",
	"hCnwBsKmGUbJ1RXNl6S+Cvz1TFv83C0XV+1U+R9FcULxOAD6VYN6vOTtj0fxoxJRb/o119QPmbY0yQNc",
	"DZyfLBKwepP/OS1nrlwXSN9cQb/7McSx2MkiUT+xNPetlFlIAQ05JpRkmXAZHK7XXQMGfgBXKQzl8yFE",
	"8WAdOf8OdeRN3cp7Xt/qNYtTmK+5oWnr0uUVi9BTZJqg/VfCEznuzEuBwP6kdL3ar/b/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
