// Package healthhttpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
//lint:file-ignore ST1005 Binding error text is generated by oapi-codegen.
package healthhttpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AIJobStatus.
const (
	Cancelled AIJobStatus = "cancelled"
	Failed    AIJobStatus = "failed"
	Queued    AIJobStatus = "queued"
	Running   AIJobStatus = "running"
	Succeeded AIJobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the AIJobStatus enum.
func (e AIJobStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for AIMediaKind.
const (
	AIMediaKindAudio AIMediaKind = "audio"
	AIMediaKindImage AIMediaKind = "image"
)

// Valid indicates whether the value is a known member of the AIMediaKind enum.
func (e AIMediaKind) Valid() bool {
	switch e {
	case AIMediaKindAudio:
		return true
	case AIMediaKindImage:
		return true
	default:
		return false
	}
}

// Defines values for AIOperation.
const (
	DietAnalysis            AIOperation = "diet_analysis"
	HealthBehaviorAnalysis  AIOperation = "health_behavior_analysis"
	HealthNutritionAnalysis AIOperation = "health_nutrition_analysis"
	HydrationCupEstimate    AIOperation = "hydration_cup_estimate"
	MealDecision            AIOperation = "meal_decision"
	MealPhotoCapture        AIOperation = "meal_photo_capture"
	MealTextCapture         AIOperation = "meal_text_capture"
	VoiceTranscription      AIOperation = "voice_transcription"
)

// Valid indicates whether the value is a known member of the AIOperation enum.
func (e AIOperation) Valid() bool {
	switch e {
	case DietAnalysis:
		return true
	case HealthBehaviorAnalysis:
		return true
	case HealthNutritionAnalysis:
		return true
	case HydrationCupEstimate:
		return true
	case MealDecision:
		return true
	case MealPhotoCapture:
		return true
	case MealTextCapture:
		return true
	case VoiceTranscription:
		return true
	default:
		return false
	}
}

// Defines values for AIRequestContractVersion.
const (
	AiRequestV1 AIRequestContractVersion = "ai-request-v1"
)

// Valid indicates whether the value is a known member of the AIRequestContractVersion enum.
func (e AIRequestContractVersion) Valid() bool {
	switch e {
	case AiRequestV1:
		return true
	default:
		return false
	}
}

// Defines values for AIRequestOptionsReasoningEffort.
const (
	High    AIRequestOptionsReasoningEffort = "high"
	Low     AIRequestOptionsReasoningEffort = "low"
	Max     AIRequestOptionsReasoningEffort = "max"
	Medium  AIRequestOptionsReasoningEffort = "medium"
	Minimal AIRequestOptionsReasoningEffort = "minimal"
)

// Valid indicates whether the value is a known member of the AIRequestOptionsReasoningEffort enum.
func (e AIRequestOptionsReasoningEffort) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Max:
		return true
	case Medium:
		return true
	case Minimal:
		return true
	default:
		return false
	}
}

// Defines values for MediaUploadAuthorizationRequestKind.
const (
	MediaUploadAuthorizationRequestKindAudio MediaUploadAuthorizationRequestKind = "audio"
	MediaUploadAuthorizationRequestKindImage MediaUploadAuthorizationRequestKind = "image"
)

// Valid indicates whether the value is a known member of the MediaUploadAuthorizationRequestKind enum.
func (e MediaUploadAuthorizationRequestKind) Valid() bool {
	switch e {
	case MediaUploadAuthorizationRequestKindAudio:
		return true
	case MediaUploadAuthorizationRequestKindImage:
		return true
	default:
		return false
	}
}

// Defines values for MediaUploadAuthorizationRequestMimeType.
const (
	Audiom4a  MediaUploadAuthorizationRequestMimeType = "audio/m4a"
	Audiomp4  MediaUploadAuthorizationRequestMimeType = "audio/mp4"
	Audiompeg MediaUploadAuthorizationRequestMimeType = "audio/mpeg"
	Audiowav  MediaUploadAuthorizationRequestMimeType = "audio/wav"
	Imageheic MediaUploadAuthorizationRequestMimeType = "image/heic"
	Imagejpeg MediaUploadAuthorizationRequestMimeType = "image/jpeg"
	Imagepng  MediaUploadAuthorizationRequestMimeType = "image/png"
)

// Valid indicates whether the value is a known member of the MediaUploadAuthorizationRequestMimeType enum.
func (e MediaUploadAuthorizationRequestMimeType) Valid() bool {
	switch e {
	case Audiom4a:
		return true
	case Audiomp4:
		return true
	case Audiompeg:
		return true
	case Audiowav:
		return true
	case Imageheic:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	default:
		return false
	}
}

// AIJob defines model for AIJob.
type AIJob struct {
	Content       *string            `json:"content,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	ErrorCategory *string            `json:"errorCategory,omitempty"`
	JobID         openapi_types.UUID `json:"jobID"`
	RequestID     openapi_types.UUID `json:"requestID"`
	Status        AIJobStatus        `json:"status"`
	UpdatedAt     time.Time          `json:"updatedAt"`
	Usage         *TokenUsage        `json:"usage,omitempty"`
}

// AIJobStatus defines model for AIJob.Status.
type AIJobStatus string

// AIMedia defines model for AIMedia.
type AIMedia struct {
	Id        string      `json:"id"`
	Kind      AIMediaKind `json:"kind"`
	MimeType  string      `json:"mimeType"`
	ObjectID  string      `json:"objectID"`
	Sha256    SHA256      `json:"sha256"`
	SizeBytes int64       `json:"sizeBytes"`
}

// AIMediaKind defines model for AIMedia.Kind.
type AIMediaKind string

// AIOperation defines model for AIOperation.
type AIOperation string

// AIRequest defines model for AIRequest.
type AIRequest struct {
	ContractVersion    AIRequestContractVersion   `json:"contractVersion"`
	Media              []AIMedia                  `json:"media"`
	Operation          AIOperation                `json:"operation"`
	Options            AIRequestOptions           `json:"options"`
	Prompt             string                     `json:"prompt"`
	PromptVersion      string                     `json:"promptVersion"`
	RecognitionSession *RecognitionSessionContext `json:"recognitionSession,omitempty"`
	RequestID          openapi_types.UUID         `json:"requestID"`

	// ResponseSchema Inline strict JSON Schema selected by the registered prompt contract.
	ResponseSchema    map[string]interface{} `json:"responseSchema"`
	SemanticSignature string                 `json:"semanticSignature"`
}

// AIRequestContractVersion defines model for AIRequest.ContractVersion.
type AIRequestContractVersion string

// AIRequestOptions defines model for AIRequestOptions.
type AIRequestOptions struct {
	ReasoningEffort  *AIRequestOptionsReasoningEffort `json:"reasoningEffort,omitempty"`
	Stream           *bool                            `json:"stream,omitempty"`
	Temperature      *float64                         `json:"temperature,omitempty"`
	WebSearchEnabled *bool                            `json:"webSearchEnabled,omitempty"`
}

// AIRequestOptionsReasoningEffort defines model for AIRequestOptions.ReasoningEffort.
type AIRequestOptionsReasoningEffort string

// AIResponse defines model for AIResponse.
type AIResponse struct {
	Content   string             `json:"content"`
	RequestID openapi_types.UUID `json:"requestID"`
	Usage     TokenUsage         `json:"usage"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestID"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// JobCapability defines model for JobCapability.
type JobCapability struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	JobID     openapi_types.UUID `json:"jobID"`

	// ResultToken Read-only result capability with the same expiresAt; absent on older gateways.
	ResultToken *string `json:"resultToken,omitempty"`
	Token       string  `json:"token"`
}

// MediaUploadAuthorization defines model for MediaUploadAuthorization.
type MediaUploadAuthorization struct {
	ExpiresAt       time.Time         `json:"expiresAt"`
	ObjectID        string            `json:"objectID"`
	RequiredHeaders map[string]string `json:"requiredHeaders"`
	UploadURL       string            `json:"uploadURL"`
}

// MediaUploadAuthorizationRequest defines model for MediaUploadAuthorizationRequest.
type MediaUploadAuthorizationRequest struct {
	Kind               MediaUploadAuthorizationRequestKind     `json:"kind"`
	MediaID            string                                  `json:"mediaID"`
	MimeType           MediaUploadAuthorizationRequestMimeType `json:"mimeType"`
	Operation          AIOperation                             `json:"operation"`
	RecognitionSession *RecognitionSessionContext              `json:"recognitionSession,omitempty"`
	RequestID          openapi_types.UUID                      `json:"requestID"`
	Sha256             SHA256                                  `json:"sha256"`
	SizeBytes          int64                                   `json:"sizeBytes"`
}

// MediaUploadAuthorizationRequestKind defines model for MediaUploadAuthorizationRequest.Kind.
type MediaUploadAuthorizationRequestKind string

// MediaUploadAuthorizationRequestMimeType defines model for MediaUploadAuthorizationRequest.MimeType.
type MediaUploadAuthorizationRequestMimeType string

// RecognitionQuotaSnapshot defines model for RecognitionQuotaSnapshot.
type RecognitionQuotaSnapshot struct {
	Completed int       `json:"completed"`
	Remaining int       `json:"remaining"`
	Reserved  int       `json:"reserved"`
	ResetAt   time.Time `json:"resetAt"`
}

// RecognitionSessionContext defines model for RecognitionSessionContext.
type RecognitionSessionContext struct {
	BusinessDayStartHour int                `json:"businessDayStartHour"`
	SessionID            openapi_types.UUID `json:"sessionID"`
	TimeZoneIdentifier   string             `json:"timeZoneIdentifier"`
}

// SHA256 defines model for SHA256.
type SHA256 = string

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	InputTokens  int `json:"inputTokens"`
	OutputTokens int `json:"outputTokens"`
}

// JobCapabilityHeader defines model for JobCapabilityHeader.
type JobCapabilityHeader = string

// JobIDHeader defines model for JobIDHeader.
type JobIDHeader = openapi_types.UUID

// JobIDPath defines model for JobIDPath.
type JobIDPath = openapi_types.UUID

// JobResultCapabilityHeader defines model for JobResultCapabilityHeader.
type JobResultCapabilityHeader = string

// RequestIDHeader defines model for RequestIDHeader.
type RequestIDHeader = openapi_types.UUID

// BadGateway defines model for BadGateway.
type BadGateway = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Error defines model for Error.
type Error = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// UpgradeRequired defines model for UpgradeRequired.
type UpgradeRequired = ErrorResponse

// IssueAIJobCapabilityParams defines parameters for IssueAIJobCapability.
type IssueAIJobCapabilityParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// EnqueueAIJobParams defines parameters for EnqueueAIJob.
type EnqueueAIJobParams struct {
	XTellyouwhatRequestID RequestIDHeader     `json:"X-Tellyouwhat-Request-ID"`
	XHealthJobID          JobIDHeader         `json:"X-Health-Job-ID"`
	XHealthJobCapability  JobCapabilityHeader `json:"X-Health-Job-Capability"`
}

// CancelAIJobParams defines parameters for CancelAIJob.
type CancelAIJobParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// GetAIJobParams defines parameters for GetAIJob.
type GetAIJobParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// DownloadAIJobResultParams defines parameters for DownloadAIJobResult.
type DownloadAIJobResultParams struct {
	XTellyouwhatRequestID      RequestIDHeader           `json:"X-Tellyouwhat-Request-ID"`
	XHealthJobResultCapability JobResultCapabilityHeader `json:"X-Health-Job-Result-Capability"`
}

// CancelRecognitionSessionParams defines parameters for CancelRecognitionSession.
type CancelRecognitionSessionParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// CompleteRecognitionSessionParams defines parameters for CompleteRecognitionSession.
type CompleteRecognitionSessionParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// CompleteAIRequestParams defines parameters for CompleteAIRequest.
type CompleteAIRequestParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// StreamAIRequestParams defines parameters for StreamAIRequest.
type StreamAIRequestParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// AuthorizeMediaUploadParams defines parameters for AuthorizeMediaUpload.
type AuthorizeMediaUploadParams struct {
	XTellyouwhatRequestID RequestIDHeader `json:"X-Tellyouwhat-Request-ID"`
}

// IssueAIJobCapabilityJSONRequestBody defines body for IssueAIJobCapability for application/json ContentType.
type IssueAIJobCapabilityJSONRequestBody = AIRequest

// EnqueueAIJobJSONRequestBody defines body for EnqueueAIJob for application/json ContentType.
type EnqueueAIJobJSONRequestBody = AIRequest

// CompleteAIRequestJSONRequestBody defines body for CompleteAIRequest for application/json ContentType.
type CompleteAIRequestJSONRequestBody = AIRequest

// StreamAIRequestJSONRequestBody defines body for StreamAIRequest for application/json ContentType.
type StreamAIRequestJSONRequestBody = AIRequest

// AuthorizeMediaUploadJSONRequestBody defines body for AuthorizeMediaUpload for application/json ContentType.
type AuthorizeMediaUploadJSONRequestBody = MediaUploadAuthorizationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// IssueAIJobCapability Issue an App Attest-bound one-time background job capability
	// (POST /v1/ai/job-capabilities)
	IssueAIJobCapability(c *gin.Context, params IssueAIJobCapabilityParams)
	// EnqueueAIJob Enqueue a background managed-AI job
	// (POST /v1/ai/jobs)
	EnqueueAIJob(c *gin.Context, params EnqueueAIJobParams)
	// CancelAIJob Cancel a queued or running background job
	// (DELETE /v1/ai/jobs/{id})
	CancelAIJob(c *gin.Context, id JobIDPath, params CancelAIJobParams)
	// GetAIJob Read a background job
	// (GET /v1/ai/jobs/{id})
	GetAIJob(c *gin.Context, id JobIDPath, params GetAIJobParams)
	// DownloadAIJobResult Wait up to four minutes for a job result for a system background download
	// (GET /v1/ai/jobs/{id}/result)
	DownloadAIJobResult(c *gin.Context, id JobIDPath, params DownloadAIJobResultParams)
	// CancelRecognitionSession Release an unfinished free meal-recognition reservation
	// (DELETE /v1/ai/recognition-sessions/{id})
	CancelRecognitionSession(c *gin.Context, id openapi_types.UUID, params CancelRecognitionSessionParams)
	// CompleteRecognitionSession Commit one successfully saved free meal-recognition session
	// (POST /v1/ai/recognition-sessions/{id}/complete)
	CompleteRecognitionSession(c *gin.Context, id openapi_types.UUID, params CompleteRecognitionSessionParams)
	// CompleteAIRequest Complete a constrained managed-AI request
	// (POST /v1/ai/requests)
	CompleteAIRequest(c *gin.Context, params CompleteAIRequestParams)
	// StreamAIRequest Stream a constrained managed-AI request as server-sent events
	// (POST /v1/ai/streams)
	StreamAIRequest(c *gin.Context, params StreamAIRequestParams)
	// AuthorizeMediaUpload Authorize a restricted temporary TOS upload
	// (POST /v1/media/upload-authorizations)
	AuthorizeMediaUpload(c *gin.Context, params AuthorizeMediaUploadParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// IssueAIJobCapability operation middleware
func (siw *ServerInterfaceWrapper) IssueAIJobCapability(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IssueAIJobCapabilityParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IssueAIJobCapability(c, params)
}

// EnqueueAIJob operation middleware
func (siw *ServerInterfaceWrapper) EnqueueAIJob(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params EnqueueAIJobParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Health-Job-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Health-Job-ID")]; found {
		var XHealthJobID JobIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Health-Job-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Health-Job-ID", valueList[0], &XHealthJobID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Health-Job-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XHealthJobID = XHealthJobID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Health-Job-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Health-Job-Capability" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Health-Job-Capability")]; found {
		var XHealthJobCapability JobCapabilityHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Health-Job-Capability, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Health-Job-Capability", valueList[0], &XHealthJobCapability, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Health-Job-Capability: %w", err), http.StatusBadRequest)
			return
		}

		params.XHealthJobCapability = XHealthJobCapability

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Health-Job-Capability is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnqueueAIJob(c, params)
}

// CancelAIJob operation middleware
func (siw *ServerInterfaceWrapper) CancelAIJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelAIJobParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelAIJob(c, id, params)
}

// GetAIJob operation middleware
func (siw *ServerInterfaceWrapper) GetAIJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAIJobParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAIJob(c, id, params)
}

// DownloadAIJobResult operation middleware
func (siw *ServerInterfaceWrapper) DownloadAIJobResult(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadAIJobResultParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Health-Job-Result-Capability" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Health-Job-Result-Capability")]; found {
		var XHealthJobResultCapability JobResultCapabilityHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Health-Job-Result-Capability, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Health-Job-Result-Capability", valueList[0], &XHealthJobResultCapability, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Health-Job-Result-Capability: %w", err), http.StatusBadRequest)
			return
		}

		params.XHealthJobResultCapability = XHealthJobResultCapability

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Health-Job-Result-Capability is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadAIJobResult(c, id, params)
}

// CancelRecognitionSession operation middleware
func (siw *ServerInterfaceWrapper) CancelRecognitionSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelRecognitionSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelRecognitionSession(c, id, params)
}

// CompleteRecognitionSession operation middleware
func (siw *ServerInterfaceWrapper) CompleteRecognitionSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteRecognitionSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteRecognitionSession(c, id, params)
}

// CompleteAIRequest operation middleware
func (siw *ServerInterfaceWrapper) CompleteAIRequest(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteAIRequestParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteAIRequest(c, params)
}

// StreamAIRequest operation middleware
func (siw *ServerInterfaceWrapper) StreamAIRequest(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamAIRequestParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamAIRequest(c, params)
}

// AuthorizeMediaUpload operation middleware
func (siw *ServerInterfaceWrapper) AuthorizeMediaUpload(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizeMediaUploadParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Tellyouwhat-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tellyouwhat-Request-ID")]; found {
		var XTellyouwhatRequestID RequestIDHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Tellyouwhat-Request-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tellyouwhat-Request-ID", valueList[0], &XTellyouwhatRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Tellyouwhat-Request-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XTellyouwhatRequestID = XTellyouwhatRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Tellyouwhat-Request-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthorizeMediaUpload(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/media/upload-authorizations", wrapper.AuthorizeMediaUpload)
	router.POST(options.BaseURL+"/v1/ai/requests", wrapper.CompleteAIRequest)
	router.POST(options.BaseURL+"/v1/ai/streams", wrapper.StreamAIRequest)
	router.DELETE(options.BaseURL+"/v1/ai/recognition-sessions/:id", wrapper.CancelRecognitionSession)
	router.POST(options.BaseURL+"/v1/ai/recognition-sessions/:id/complete", wrapper.CompleteRecognitionSession)
	router.POST(options.BaseURL+"/v1/ai/job-capabilities", wrapper.IssueAIJobCapability)
	router.POST(options.BaseURL+"/v1/ai/jobs", wrapper.EnqueueAIJob)
	router.DELETE(options.BaseURL+"/v1/ai/jobs/:id", wrapper.CancelAIJob)
	router.GET(options.BaseURL+"/v1/ai/jobs/:id", wrapper.GetAIJob)
	router.GET(options.BaseURL+"/v1/ai/jobs/:id/result", wrapper.DownloadAIJobResult)
}

type BadGatewayJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ErrorJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type PayloadTooLargeJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type TooManyRequestsJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnprocessableEntityJSONResponse ErrorResponse

type UpgradeRequiredJSONResponse ErrorResponse

type IssueAIJobCapabilityRequestObject struct {
	Params IssueAIJobCapabilityParams
	Body   *IssueAIJobCapabilityJSONRequestBody
}

type IssueAIJobCapabilityResponseObject interface {
	VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error
}

type IssueAIJobCapability201JSONResponse JobCapability

func (response IssueAIJobCapability201JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IssueAIJobCapability401JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability403JSONResponse struct{ ForbiddenJSONResponse }

func (response IssueAIJobCapability403JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability409JSONResponse struct{ ConflictJSONResponse }

func (response IssueAIJobCapability409JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response IssueAIJobCapability413JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response IssueAIJobCapability422JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability426JSONResponse struct{ UpgradeRequiredJSONResponse }

func (response IssueAIJobCapability426JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response IssueAIJobCapability429JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapability503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response IssueAIJobCapability503JSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type IssueAIJobCapabilitydefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response IssueAIJobCapabilitydefaultJSONResponse) VisitIssueAIJobCapabilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJobRequestObject struct {
	Params EnqueueAIJobParams
	Body   *EnqueueAIJobJSONRequestBody
}

type EnqueueAIJobResponseObject interface {
	VisitEnqueueAIJobResponse(w http.ResponseWriter) error
}

type EnqueueAIJob202JSONResponse AIJob

func (response EnqueueAIJob202JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response EnqueueAIJob401JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob403JSONResponse struct{ ForbiddenJSONResponse }

func (response EnqueueAIJob403JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob409JSONResponse struct{ ConflictJSONResponse }

func (response EnqueueAIJob409JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response EnqueueAIJob413JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response EnqueueAIJob422JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob426JSONResponse struct{ UpgradeRequiredJSONResponse }

func (response EnqueueAIJob426JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJob503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response EnqueueAIJob503JSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type EnqueueAIJobdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response EnqueueAIJobdefaultJSONResponse) VisitEnqueueAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAIJobRequestObject struct {
	Id     JobIDPath `json:"id"`
	Params CancelAIJobParams
}

type CancelAIJobResponseObject interface {
	VisitCancelAIJobResponse(w http.ResponseWriter) error
}

type CancelAIJob204Response struct {
}

func (response CancelAIJob204Response) VisitCancelAIJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelAIJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CancelAIJob401JSONResponse) VisitCancelAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAIJob404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelAIJob404JSONResponse) VisitCancelAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAIJob409JSONResponse struct{ ConflictJSONResponse }

func (response CancelAIJob409JSONResponse) VisitCancelAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAIJob503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CancelAIJob503JSONResponse) VisitCancelAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAIJobdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CancelAIJobdefaultJSONResponse) VisitCancelAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJobRequestObject struct {
	Id     JobIDPath `json:"id"`
	Params GetAIJobParams
}

type GetAIJobResponseObject interface {
	VisitGetAIJobResponse(w http.ResponseWriter) error
}

type GetAIJob200JSONResponse AIJob

func (response GetAIJob200JSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAIJob401JSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJob404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAIJob404JSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJob409JSONResponse struct{ ConflictJSONResponse }

func (response GetAIJob409JSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJob503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetAIJob503JSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAIJobdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetAIJobdefaultJSONResponse) VisitGetAIJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAIJobResultRequestObject struct {
	Id     JobIDPath `json:"id"`
	Params DownloadAIJobResultParams
}

type DownloadAIJobResultResponseObject interface {
	VisitDownloadAIJobResultResponse(w http.ResponseWriter) error
}

type DownloadAIJobResult200JSONResponse AIJob

func (response DownloadAIJobResult200JSONResponse) VisitDownloadAIJobResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAIJobResult401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DownloadAIJobResult401JSONResponse) VisitDownloadAIJobResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAIJobResult404JSONResponse struct{ NotFoundJSONResponse }

func (response DownloadAIJobResult404JSONResponse) VisitDownloadAIJobResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAIJobResult503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response DownloadAIJobResult503JSONResponse) VisitDownloadAIJobResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadAIJobResultdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DownloadAIJobResultdefaultJSONResponse) VisitDownloadAIJobResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRecognitionSessionRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params CancelRecognitionSessionParams
}

type CancelRecognitionSessionResponseObject interface {
	VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error
}

type CancelRecognitionSession204Response struct {
}

func (response CancelRecognitionSession204Response) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelRecognitionSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CancelRecognitionSession401JSONResponse) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRecognitionSession409JSONResponse struct{ ConflictJSONResponse }

func (response CancelRecognitionSession409JSONResponse) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRecognitionSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CancelRecognitionSession422JSONResponse) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRecognitionSession503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CancelRecognitionSession503JSONResponse) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRecognitionSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CancelRecognitionSessiondefaultJSONResponse) VisitCancelRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSessionRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params CompleteRecognitionSessionParams
}

type CompleteRecognitionSessionResponseObject interface {
	VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error
}

type CompleteRecognitionSession200JSONResponse RecognitionQuotaSnapshot

func (response CompleteRecognitionSession200JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CompleteRecognitionSession401JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSession404JSONResponse struct{ NotFoundJSONResponse }

func (response CompleteRecognitionSession404JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSession409JSONResponse struct{ ConflictJSONResponse }

func (response CompleteRecognitionSession409JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CompleteRecognitionSession422JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSession503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CompleteRecognitionSession503JSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteRecognitionSessiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CompleteRecognitionSessiondefaultJSONResponse) VisitCompleteRecognitionSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequestRequestObject struct {
	Params CompleteAIRequestParams
	Body   *CompleteAIRequestJSONRequestBody
}

type CompleteAIRequestResponseObject interface {
	VisitCompleteAIRequestResponse(w http.ResponseWriter) error
}

type CompleteAIRequest200JSONResponse AIResponse

func (response CompleteAIRequest200JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CompleteAIRequest401JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest403JSONResponse struct{ ForbiddenJSONResponse }

func (response CompleteAIRequest403JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest409JSONResponse struct{ ConflictJSONResponse }

func (response CompleteAIRequest409JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response CompleteAIRequest413JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CompleteAIRequest422JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest426JSONResponse struct{ UpgradeRequiredJSONResponse }

func (response CompleteAIRequest426JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CompleteAIRequest429JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest502JSONResponse struct{ BadGatewayJSONResponse }

func (response CompleteAIRequest502JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequest503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CompleteAIRequest503JSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAIRequestdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CompleteAIRequestdefaultJSONResponse) VisitCompleteAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequestRequestObject struct {
	Params StreamAIRequestParams
	Body   *StreamAIRequestJSONRequestBody
}

type StreamAIRequestResponseObject interface {
	VisitStreamAIRequestResponse(w http.ResponseWriter) error
}

type StreamAIRequest200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamAIRequest200TexteventStreamResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type StreamAIRequest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StreamAIRequest401JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest403JSONResponse struct{ ForbiddenJSONResponse }

func (response StreamAIRequest403JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest409JSONResponse struct{ ConflictJSONResponse }

func (response StreamAIRequest409JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response StreamAIRequest413JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response StreamAIRequest422JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest426JSONResponse struct{ UpgradeRequiredJSONResponse }

func (response StreamAIRequest426JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response StreamAIRequest429JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequest503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response StreamAIRequest503JSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type StreamAIRequestdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response StreamAIRequestdefaultJSONResponse) VisitStreamAIRequestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUploadRequestObject struct {
	Params AuthorizeMediaUploadParams
	Body   *AuthorizeMediaUploadJSONRequestBody
}

type AuthorizeMediaUploadResponseObject interface {
	VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error
}

type AuthorizeMediaUpload201JSONResponse MediaUploadAuthorization

func (response AuthorizeMediaUpload201JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthorizeMediaUpload401JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload403JSONResponse struct{ ForbiddenJSONResponse }

func (response AuthorizeMediaUpload403JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload409JSONResponse struct{ ConflictJSONResponse }

func (response AuthorizeMediaUpload409JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response AuthorizeMediaUpload413JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response AuthorizeMediaUpload422JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUpload503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response AuthorizeMediaUpload503JSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type AuthorizeMediaUploaddefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AuthorizeMediaUploaddefaultJSONResponse) VisitAuthorizeMediaUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// IssueAIJobCapability Issue an App Attest-bound one-time background job capability
	// (POST /v1/ai/job-capabilities)
	IssueAIJobCapability(ctx context.Context, request IssueAIJobCapabilityRequestObject) (IssueAIJobCapabilityResponseObject, error)
	// EnqueueAIJob Enqueue a background managed-AI job
	// (POST /v1/ai/jobs)
	EnqueueAIJob(ctx context.Context, request EnqueueAIJobRequestObject) (EnqueueAIJobResponseObject, error)
	// CancelAIJob Cancel a queued or running background job
	// (DELETE /v1/ai/jobs/{id})
	CancelAIJob(ctx context.Context, request CancelAIJobRequestObject) (CancelAIJobResponseObject, error)
	// GetAIJob Read a background job
	// (GET /v1/ai/jobs/{id})
	GetAIJob(ctx context.Context, request GetAIJobRequestObject) (GetAIJobResponseObject, error)
	// DownloadAIJobResult Wait up to four minutes for a job result for a system background download
	// (GET /v1/ai/jobs/{id}/result)
	DownloadAIJobResult(ctx context.Context, request DownloadAIJobResultRequestObject) (DownloadAIJobResultResponseObject, error)
	// CancelRecognitionSession Release an unfinished free meal-recognition reservation
	// (DELETE /v1/ai/recognition-sessions/{id})
	CancelRecognitionSession(ctx context.Context, request CancelRecognitionSessionRequestObject) (CancelRecognitionSessionResponseObject, error)
	// CompleteRecognitionSession Commit one successfully saved free meal-recognition session
	// (POST /v1/ai/recognition-sessions/{id}/complete)
	CompleteRecognitionSession(ctx context.Context, request CompleteRecognitionSessionRequestObject) (CompleteRecognitionSessionResponseObject, error)
	// CompleteAIRequest Complete a constrained managed-AI request
	// (POST /v1/ai/requests)
	CompleteAIRequest(ctx context.Context, request CompleteAIRequestRequestObject) (CompleteAIRequestResponseObject, error)
	// StreamAIRequest Stream a constrained managed-AI request as server-sent events
	// (POST /v1/ai/streams)
	StreamAIRequest(ctx context.Context, request StreamAIRequestRequestObject) (StreamAIRequestResponseObject, error)
	// AuthorizeMediaUpload Authorize a restricted temporary TOS upload
	// (POST /v1/media/upload-authorizations)
	AuthorizeMediaUpload(ctx context.Context, request AuthorizeMediaUploadRequestObject) (AuthorizeMediaUploadResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// IssueAIJobCapability operation middleware
func (sh *strictHandler) IssueAIJobCapability(ctx *gin.Context, params IssueAIJobCapabilityParams) {
	var request IssueAIJobCapabilityRequestObject

	request.Params = params

	var body IssueAIJobCapabilityJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.IssueAIJobCapability(ctx, request.(IssueAIJobCapabilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IssueAIJobCapability")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(IssueAIJobCapabilityResponseObject); ok {
		if err := validResponse.VisitIssueAIJobCapabilityResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnqueueAIJob operation middleware
func (sh *strictHandler) EnqueueAIJob(ctx *gin.Context, params EnqueueAIJobParams) {
	var request EnqueueAIJobRequestObject

	request.Params = params

	var body EnqueueAIJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnqueueAIJob(ctx, request.(EnqueueAIJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnqueueAIJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(EnqueueAIJobResponseObject); ok {
		if err := validResponse.VisitEnqueueAIJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelAIJob operation middleware
func (sh *strictHandler) CancelAIJob(ctx *gin.Context, id JobIDPath, params CancelAIJobParams) {
	var request CancelAIJobRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelAIJob(ctx, request.(CancelAIJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelAIJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CancelAIJobResponseObject); ok {
		if err := validResponse.VisitCancelAIJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAIJob operation middleware
func (sh *strictHandler) GetAIJob(ctx *gin.Context, id JobIDPath, params GetAIJobParams) {
	var request GetAIJobRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAIJob(ctx, request.(GetAIJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAIJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAIJobResponseObject); ok {
		if err := validResponse.VisitGetAIJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadAIJobResult operation middleware
func (sh *strictHandler) DownloadAIJobResult(ctx *gin.Context, id JobIDPath, params DownloadAIJobResultParams) {
	var request DownloadAIJobResultRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadAIJobResult(ctx, request.(DownloadAIJobResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadAIJobResult")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DownloadAIJobResultResponseObject); ok {
		if err := validResponse.VisitDownloadAIJobResultResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelRecognitionSession operation middleware
func (sh *strictHandler) CancelRecognitionSession(ctx *gin.Context, id openapi_types.UUID, params CancelRecognitionSessionParams) {
	var request CancelRecognitionSessionRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelRecognitionSession(ctx, request.(CancelRecognitionSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelRecognitionSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CancelRecognitionSessionResponseObject); ok {
		if err := validResponse.VisitCancelRecognitionSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteRecognitionSession operation middleware
func (sh *strictHandler) CompleteRecognitionSession(ctx *gin.Context, id openapi_types.UUID, params CompleteRecognitionSessionParams) {
	var request CompleteRecognitionSessionRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteRecognitionSession(ctx, request.(CompleteRecognitionSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteRecognitionSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CompleteRecognitionSessionResponseObject); ok {
		if err := validResponse.VisitCompleteRecognitionSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteAIRequest operation middleware
func (sh *strictHandler) CompleteAIRequest(ctx *gin.Context, params CompleteAIRequestParams) {
	var request CompleteAIRequestRequestObject

	request.Params = params

	var body CompleteAIRequestJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteAIRequest(ctx, request.(CompleteAIRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteAIRequest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CompleteAIRequestResponseObject); ok {
		if err := validResponse.VisitCompleteAIRequestResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamAIRequest operation middleware
func (sh *strictHandler) StreamAIRequest(ctx *gin.Context, params StreamAIRequestParams) {
	var request StreamAIRequestRequestObject

	request.Params = params

	var body StreamAIRequestJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StreamAIRequest(ctx, request.(StreamAIRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamAIRequest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StreamAIRequestResponseObject); ok {
		if err := validResponse.VisitStreamAIRequestResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthorizeMediaUpload operation middleware
func (sh *strictHandler) AuthorizeMediaUpload(ctx *gin.Context, params AuthorizeMediaUploadParams) {
	var request AuthorizeMediaUploadRequestObject

	request.Params = params

	var body AuthorizeMediaUploadJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthorizeMediaUpload(ctx, request.(AuthorizeMediaUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthorizeMediaUpload")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AuthorizeMediaUploadResponseObject); ok {
		if err := validResponse.VisitAuthorizeMediaUploadResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzNchs5cH4VFLLHISnJsmIzJ1ryrun1rh39JKlYit2caZKwZ4AxgKFEq3jINbe8QS55hlSlKm+TfY8U",
	"gPnBkENxKMmysysfXCSIn0b/fOhGN3RNQ5GkgiPXivavaQoSEtQo7bfXYnQIKYxYzPT8FUKE0jQzTvt0",
	"6r4GlEOCtE//qfMKIdbTzmsx6lSjaEAlfsmYxIj2tcwwoCqcYgJmooTxN8gnekr7uwHV89RMpLRkfEIX",
	"i8CsPzzaZt3h0Y3rjYVMQNM+zTIW0bUrvgNDUb5ear6Uq9lhd1zgGFUW69sx1o29L/4e45cMlW7B41OM",
	"47nILqegO/mouzJ7YQarVHCFVtleQPQLaLyEufkWCq6Ra/MR0jRmIWgmeO+TEty0Vcv8JHFM+/RvepUi",
	"99yvqvdSSiGP80XckhGqULLUTEb79HSKJAEOE4zIYEhSKWYsQknGwGKMunQR0EPBxzEL9cMRNSAS0xjm",
	"AWERJqnQyMN5QIQkSoNGEuYUERGGmZQ5nXbaBySSEzR9SCFDS8TPQo5YFCF/WBGGEMcoCVMEMj1Frs1a",
	"GJFRpkkM4WdF9BRJoarEdNAxJsi1pfp3oX8WGY8elmgpMo3EcVBkMkQSCVSEC03wiilNxkISPWUq354l",
	"9R3MYwHRqRBvQE7wgSl2hk/wKkSMFAFORIrSrtdRKYZszEKi2FckMUuYY+4JyhkL8YzDDFgMoxgf1pJy",
	"mStHBokwRR4ZizLqklVUWWJPhfgN+DxHOPWglILGwNi2tWlr8RGw2Bl+IriexnOiYIx67rhLLkERiRBO",
	"cwQ440b7hWRf8QFVeVBZHBPcECs4djRLjFkWpxSZQcwi18PD1jOeShGiUkYAL41Vzr+PRs+YiEGjw4ni",
	"QBhlinFUyghFSwidPp+lEwkRHpfn3oMCXU6JYXMqRZJqMkOpDFuZgQ4SCz5BSVSWpkJqy+ZFcShbdR4M",
	"X4uRpTSKmJkZ4nfSWLFm5hgeQ6wwoKnXVNvf0iEe0FCigdqBrh35EWinA6vnfkDtuXEIGidCzhsn/WS8",
	"sBY+hHM/rAfTqrc5PzO7JeRZQvvv6ZcMM7Q+Xca56RVQlYUG3myr01Ua0BB4iLH5fNEwb5ZG2zIhU+Dg",
	"+yadOBWfkZ/ZnouF72u9z1nkM6Dcni8Un7aKcjH6hKE2ZAyGv2HEYEuFYFbtE7gqvMvnB8HNzmZAPzN3",
	"wBacZ4nZVkAhi5ho5GrCEjy1jQ0q4rbg5L5hZTWFvacHm3h98mpgepn+7Cu+mGu31VKajOuDfRqYXbPE",
	"bGHvYG93f39nx+7cNVWrM65xgnJFbFYvLSu8/Xm7Kan1yWgW3Nvi6PW5OhMsxA9aAq+gI6AJQvwhnQot",
	"PoSQ6kyaNafzyI3/EGbpB1SaJaCx6K3xSnudbVuEIVNuxoih/gAc4rliRuOmNkT5wDMtrRI1/DbCKcyY",
	"kNVPTUIfDPPD9xYYZZDxHxwc5k1mGgqsk1tJZ7bbZItJYQJMY6I2KUphMgurC0M3ZL+cFqSEudVQXz43",
	"T1iJ0o4zn1qQkTPqbd5/YVmSpHrJNp/u7e89e7bRPt1Yj30b+ksMxYRb8ZygUi32ebwy4tAcLFd6eyAv",
	"go6T8mhtVhUXk9bP0SGPGUdiJgs1eX3y9nfipiEKYwxt3DDPA4YJUxqN+5gftpUn0GCSChMwjtAJm3Cw",
	"dlMXxN7TTSi5BBY+tlfaFKzo+rLwSkVYYVSlXYXWN5HdjDdL6radeUoEJcwB+3I8FlL7kGXRE2Ia0Fhc",
	"5nRlicENNpk6wG1ECqUlQmJminAMWazLpfOuIyFiBGtTGhPLv1wo1REtMhOQ+KjuwflOORXPkpFB84Be",
	"4ugEQYbTl9w4rVGb9Rdr+Jn7evfnjG1nRHd1QXz1LKgqZm1SIevhHqEGFm+956jZC0hM7DDBzcy42dDs",
	"/NVs/ti1G7ml+LC4ptkYC+ScWqbVTdBEVu22dluyrlImUW3jwW7jpKss1laTnLn4cHyMEHUEj+fEdfOj",
	"xkumpxaJFSRIShr/jsBIIdfExJtxhJJM3MWh6tKN55wuyNgGiQtv2w0OPHY1CcL6B2dpLCAa5BF56Qh8",
	"W5n4XnGjQZgNucveGxC8YezKHjO7vbPjN3UNkIxu4qXn61aTrFJ3Wybfzn28RXRi1s/jj60CIT+sqS3X",
	"+5SiCUDdlymysPyS2sjUEtNL9qH6nO57n7HqdAmzRqpv65R+V2/vRwrg1vlkhTo0RXctQzqPY3+fCQ0n",
	"HFI1FdtHQkkao3auSYMvU+7MbCwBZq89WnRVKGftJlWo24PWylFcUO+t6VNaLbCBh0tatx0Ti7u/I5if",
	"aJD6lchkbuq58jwJNvBBufVb6rhhzj8LjsMIuWZjhnIJWQ72twsequWD5t00rtnE09ywbHZYa5Tm1P6X",
	"99AZ73SeX1wf7C9+atqQ5zhuebnE08w5C2qzsolMt+69fBXjrbM00SoXrDzDTDI9t6GUI3WQpgOtUemB",
	"UmYDosG/eQEKD/Y7yI2TGZFBmhI3hkAxKM/0IAmBC85CiMuL6RHjEeMT49e0yMxWZFTXESn7Fe19REns",
	"rzh3SrnsiJXRrkfkZ5wTVupHSzp+xbnLDq8n4nfBQ1wl4m2ZO5hCHCOfIJlBnGHLhd2sN6177J889bXf",
	"iEuUISgkZ2fDIzISGY8I41pY2ZTSaklKLUu+np5TlqDSkKQNAvn5kDx58uS5pyi66N2SiGr2BhqOcIax",
	"SBPkehBqNiv9ghYTH+Gs4w1qmL0WjdSTRKtbPWITwyvH8jJ/NILw80Tatk9i5AUGN+x+XRFKE31NSvBa",
	"jBrF35DUakdFs/zLMpBNnHlpnGDGJ0RiZtNkRJYBkxcpjV3ezfCpHVlNhSRLVBrQY3wsVok6LHFqkKZV",
	"5rf0h1SJaH/8+7/97//8xx//+p9//Pd/FYm1zmBYBGzdc346RTJBbkZiRNJsFLOwynNBrARhPIyzKM/O",
	"qSkYiHoXgzaH6uDdsHtuFZDp2FDv9kh+q6o6Bu+GNKCz4maT7nZ3uju5M8whZbRPn3R3uzs0sMU+Ftl7",
	"7tL6K+1fLwLaMzyfF19muz1gvU9i1CkFkB9dqXCBR8mIYUT7dKhUhjbvVuO2X2r1vtm1rbr0lkt1Fhel",
	"F/1CRPeXNq3u3xf1A1PLDJdLdvZ2du9t4Tp7GlPkUSNKLEPDIqD7jq6m5Ur6e7V0uR30ZPOgqsDFjni+",
	"eURZP2QG7LZYYrnEw4zb22uzn9Vkuh170GLsUlLbjmuxueV6iUVAn7ZhY0NRiJV3fo+6abirdfKdMmtC",
	"Te7Y+4tVz6fWljsitTbPSai1e4f1+wtjgSpLEpDzwsgJcM93an2cGfSCiYGBHL2oPSAUvVjU8OYGjHnJ",
	"bSbbZffvjC3BxiF+ZWa77iv1jj8Igu3d48KG+WsqN6JM2tN7SQkuQREIQ0x1XhLzCF13h64fAYKWIORG",
	"bzjv4PrWYSW3awK+4nh+1Cdr7u3Qo3fNooVz5mLUuAoih7bI5Z4w5GLF0vZXHUljGYUZlCU2d7GD/c2D",
	"ymrP25jBX/R0c5pBgLh6KVu16gqmlgDtBmUM6AQbTq5fUH8zjdv59th+aKs19TKu20rtR0X+4RT5GCGq",
	"g+kmpd1OKav3I4uLBvTtuRynYV1uDMt3cDcF+c6f1KKI9AkY9/KSo+ySAeFGz2XCuL0+dDIwoEpGSCJx",
	"yc3JjBGBCTBuM6si0zbnOkqY1saUGR+jRB5ilxTZbUWSTGlblD4ys7li42DJho/y6a2VuJsFegfOBd/I",
	"Y13z8Ob7AMdpIasSLmyld5jjiXvqAWON7iLFyh4jcgl5Xf3D4Mp3hIm1V2TLNv2PwDTJUmMYY5FJkjCe",
	"aXR3UGDZm1cWuAY1VxoTHwIK62jlSX3JhIbaTZCXG+3kWZe2vtZquupegrf7f7jWyps7tvk6V+UvMUZQ",
	"GFmltlFObC/R8tKNXpnnu4sybxvD3CEW+cuel1aMBDjJ+JhxpqYYkbFEJAlC3PF0n8hK/E2WNBjW7Git",
	"1ZSqsf624zDv8f/YfO7vhFlbNtBw6Hh9Sc50EorEOADGVN1Fu3UFipeHOn+MqH5kZ/bRsLeP6KzUrSdp",
	"H7woNc5i+8JsttbAVWljm427ekB3swlXt3V/kozIzr0ufNOLQdevkz+tw9q9kPN4Hm8Uv3sypAWt3sP3",
	"vzQeWTwgQOy7HQmML6t0gROb0Me9DKiBz1JSPWFakY8Rxho+Bia+4hYJy/j5Y+mefiQ4Q667ZMDJR1t7",
	"nbeY0Pq8iLgt3W7ZPGYrI3CXhVdkCjMsneARooFTrl3uug6NJ3aePz0warzSPcvKTvWUA6/AMN4vZMzL",
	"ImwZEO1TO6JPrOzOeQQa+uT6nLrvtH9Ou93uOV2c83Oedy1l6XUvyzjtkJ38X8f+t2/+e1Z8Lf6d0+C8",
	"IN8Oul7YJvve4Zz2r8/9irJz2t8NzmtVZaZpsfDe4za9S2iCeZQzlB1b8O40z7HrEdwfM93fA6lPcpjb",
	"gNME1Krqqo3onaYdpYXEHheajXNgUt59iyWvV5YHrv70GedeY4Sznvf3PlQPXNUaVl1qP9uns6ZPbVVb",
	"3d1zzxU64D83uMHFLZ4loPdU4YcF803PKR64GmjtE5o1f+XDvebEiGgTt0qQc+Kk5e6eSvh7BM3H8Hfu",
	"2yaBZu05fXuSa1ATZLkX4CVqpZLNIJz3DCLmf0lt6RfjePitIspCrXoFbAIzP1oGGcR0yFDX8ndujIu/",
	"MxnTPp1qnap+rwcp67p6xa6uanS7Ibe3WctFziHEJKpKf2uz9Xu93b2/7e50d7q7/Wc7z3Ys3uTbvy4u",
	"w4raSzt93pariN+UU6z8NieY4llR2fzSg+D6FJZ9tRnSNK4tkwvFayne51djhv43e6W/uFj8XwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
