package voice

import "slices"

// TablePatch is a sparse document operation. The model supplies only changed
// data; original values, IDs and provenance are never regenerated by the model.
// These operations are materialized against the exact request snapshot before
// a revision can be offered to the app. Source authorization is a separate gate.
type TablePatch struct {
	Kind     string       `json:"kind"`
	TargetID string       `json:"targetID"`
	Title    string       `json:"title"`
	Cell     *TableCell   `json:"cell"`
	Row      *TableRow    `json:"row"`
	Column   *TableColumn `json:"column"`
	Order    []string     `json:"order"`
}

func applyTablePatches(before TableContext, patches []TablePatch) (TableContext, error) {
	if len(patches) == 0 || len(patches) > 128 {
		return TableContext{}, ErrInvalid
	}
	result := before
	result.Columns = slices.Clone(before.Columns)
	result.Rows = slices.Clone(before.Rows)
	for i := range result.Rows {
		result.Rows[i].Cells = slices.Clone(result.Rows[i].Cells)
	}
	claimed := map[string]bool{before.BlockID: true, before.TableID: true}
	for _, c := range before.Columns {
		claimed[c.ID] = true
	}
	for _, r := range before.Rows {
		claimed[r.ID] = true
	}
	claim := func(id string) bool {
		if !validID(id) || claimed[id] {
			return false
		}
		claimed[id] = true
		return true
	}
	for _, p := range patches {
		row := slices.IndexFunc(result.Rows, func(r TableRow) bool { return r.ID == p.TargetID })
		column := slices.IndexFunc(result.Columns, func(c TableColumn) bool { return c.ID == p.TargetID })
		// Unused payload fields are rejected, not silently interpreted later.
		if (p.Cell != nil) != (p.Kind == "setCell") || (p.Row != nil) != (p.Kind == "insertRow") ||
			(p.Column != nil) != (p.Kind == "insertColumn") ||
			(len(p.Order) > 0 && p.Kind != "orderRows" && p.Kind != "orderColumns") ||
			(p.Title != "" && p.Kind != "renameTable" && p.Kind != "renameColumn") {
			return TableContext{}, ErrInvalid
		}
		switch p.Kind {
		case "setCell":
			if row < 0 || !validateTableCellValue(*p.Cell) {
				return TableContext{}, ErrInvalid
			}
			cell := slices.IndexFunc(result.Rows[row].Cells, func(c TableCell) bool { return c.ColumnID == p.Cell.ColumnID })
			if cell < 0 {
				return TableContext{}, ErrInvalid
			}
			result.Rows[row].Cells[cell] = *p.Cell
		case "renameTable":
			if p.TargetID != before.TableID {
				return TableContext{}, ErrInvalid
			}
			result.Title = p.Title
		case "renameColumn":
			if column < 0 {
				return TableContext{}, ErrInvalid
			}
			result.Columns[column].Title = p.Title
		case "insertRow":
			if !claim(p.Row.ID) || (p.TargetID != "" && row < 0) {
				return TableContext{}, ErrInvalid
			}
			newRow := *p.Row
			newRow.Cells = slices.Clone(p.Row.Cells)
			result.Rows = slices.Insert(result.Rows, row+1, newRow)
		case "insertColumn":
			if !claim(p.Column.ID) || (p.TargetID != "" && column < 0) {
				return TableContext{}, ErrInvalid
			}
			result.Columns = slices.Insert(result.Columns, column+1, *p.Column)
			for i := range result.Rows {
				result.Rows[i].Cells = append(result.Rows[i].Cells, TableCell{ColumnID: p.Column.ID, Kind: "pending"})
			}
		case "deleteRow":
			if row < 0 {
				return TableContext{}, ErrInvalid
			}
			result.Rows = slices.Delete(result.Rows, row, row+1)
		case "deleteColumn":
			if column < 0 {
				return TableContext{}, ErrInvalid
			}
			result.Columns = slices.Delete(result.Columns, column, column+1)
			for i := range result.Rows {
				result.Rows[i].Cells = slices.DeleteFunc(result.Rows[i].Cells, func(c TableCell) bool { return c.ColumnID == p.TargetID })
			}
		case "orderRows":
			if p.TargetID != before.TableID || len(p.Order) != len(result.Rows) {
				return TableContext{}, ErrInvalid
			}
			ordered := make([]TableRow, 0, len(p.Order))
			seen := map[string]bool{}
			for _, id := range p.Order {
				i := slices.IndexFunc(result.Rows, func(r TableRow) bool { return r.ID == id })
				if i < 0 || seen[id] {
					return TableContext{}, ErrInvalid
				}
				seen[id] = true
				ordered = append(ordered, result.Rows[i])
			}
			result.Rows = ordered
		case "orderColumns":
			if p.TargetID != before.TableID || len(p.Order) != len(result.Columns) {
				return TableContext{}, ErrInvalid
			}
			ordered := make([]TableColumn, 0, len(p.Order))
			seen := map[string]bool{}
			for _, id := range p.Order {
				i := slices.IndexFunc(result.Columns, func(c TableColumn) bool { return c.ID == id })
				if i < 0 || seen[id] {
					return TableContext{}, ErrInvalid
				}
				seen[id] = true
				ordered = append(ordered, result.Columns[i])
			}
			result.Columns = ordered
		default:
			return TableContext{}, ErrInvalid
		}
		// Validate every intermediate shape and budget, while retaining source
		// evidence in the result for the revision's dedicated evidence validator.
		shape := result
		shape.Rows = slices.Clone(result.Rows)
		for i := range shape.Rows {
			shape.Rows[i].Cells = slices.Clone(result.Rows[i].Cells)
			for j := range shape.Rows[i].Cells {
				shape.Rows[i].Cells[j].Sources = nil
			}
		}
		if err := validateTableContext(Snapshot{Blocks: []Block{{ID: before.BlockID}}, BlockComponents: map[string][]string{before.BlockID: {before.TableID}}, TableContext: []TableContext{shape}}); err != nil {
			return TableContext{}, err
		}
	}
	return result, nil
}
